Sources/WalletConnect/Engine/PairingEngine.swift, Sources/WalletConnect/Relay/WalletConnectRelay.swift, Tests/WalletConnectTests/PairingEngineTests.swift
Binds pairing engine response acknowledgement to relayer's `onResponse`
=> Bind pairing engine responses

Sources/WalletConnect/Engine/PairingEngine.swift, Sources/WalletConnect/Relay/WalletConnectRelay.swift, Tests/WalletConnectTests/Mocks/MockedRelay.swift, Tests/WalletConnectTests/PairingEngineTests.swift
Fast workaround fix for pairing response handling on failed approval. Needs a better solution in the future.
=> Fast workaround fix for pairing responses

Example/ExampleApp.xcodeproj/project.pbxproj, Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Example/ExampleApp/Proposer/ProposerViewController.swift, Example/ExampleApp/Responder/Request/RequestViewController.swift, Example/ExampleApp/Responder/ResponderViewController.swift, Example/ExampleApp/Responder/UIAlertController.swift, Example/ExampleApp/SceneDelegate.swift, Sources/Relayer/SocketConnectionObserving.swift
- add personal_sign, eth_signTypedData, eth_sendTransaction signing for example app
- fix networking issue
- add description on request screen
=> Message signing

Sources/WalletConnect/Extensions/String.swift, Tests/WalletConnectTests/String+ExtensionTests.swift
closes #33 
Adds extension methods to `String` to validate formatting standards for:
- CAIP-2 Chain IDs.
- CAIP-10 Account IDs.
Reference:
https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-2.md
https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-10.md
=> #33 Validation for CAIP-2 and CAIP-10

Sources/WalletConnect/Types/WalletConnectURI.swift, Sources/WalletConnect/WalletConnectClientDelegate.swift
We need to pass around `WalletConnectURI` before paring and typed uri is always safer than `string`, also it might better to have a `public func pair(uri: WalletConnectURI)` method in `WalletConnectClient`
=> Make `WalletConnectURI` public

Sources/WalletConnect/Engine/PairingEngine.swift, Sources/WalletConnect/Engine/SessionEngine.swift, Sources/WalletConnect/Extensions/String+Extension.swift, Sources/WalletConnectKMS/Crypto/Random.swift, Sources/WalletConnectUtils/Data+Extension.swift, Tests/WalletConnectKMSTests/AgreementSecret+Stub.swift, Tests/WalletConnectTests/Helpers/TopicGenerator.swift, Tests/WalletConnectTests/SequenceStoreTests.swift, Tests/WalletConnectTests/SessionEngineTests.swift, Tests/WalletConnectTests/Stub/AgreementSecret+Stub.swift, Tests/WalletConnectTests/Stub/Session+Stub.swift, Tests/WalletConnectTests/Stub/Stubs.swift, Tests/WalletConnectTests/Stub/WalletConnectURI+Stub.swift
closes #96
Moves the security random bytes generator function to the Utils package. Also removes the optional return, as generating secure random data is a premise to the protocol standard.
=> #96 Move secure random bytes generator to Utils

Sources/WalletConnect/Types/Common/AppMetadata.swift, Tests/IntegrationTests/ClientTest.swift, Tests/WalletConnectTests/PairingEngineTests.swift, Tests/WalletConnectTests/SessionEngineTests.swift, Tests/WalletConnectTests/Stub/Stubs.swift
All metadata fields are required, so they are being changed to non-optionals.
Also, adds API documentation for the `AppMetadata` struct.
=> Remove optionals from AppMetadata, adds documentation

Sources/WalletConnect/Account.swift, Sources/WalletConnect/Blockchain.swift, Sources/WalletConnect/Engine/SessionEngine.swift, Sources/WalletConnect/Types/Session/SessionProposal.swift, Sources/WalletConnect/Types/Session/SessionSequence.swift, Sources/WalletConnect/Types/Session/SessionType.swift, Tests/WalletConnectTests/AccountTests.swift, Tests/WalletConnectTests/BlockchainTests.swift, Tests/WalletConnectTests/Stub/Session+Stub.swift, Tests/WalletConnectTests/Stub/Stubs.swift
closes #131
Adds the `Blockchain` type conforming to [CAIP-2](https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-2.md).
=> CAIP-2 Blockchain Type

Sources/WalletConnectUtils/AnyCodable.swift, Tests/TestingUtils/Helpers.swift, Tests/WalletConnectTests/AnyCodableTests.swift, Tests/WalletConnectTests/Helpers/HelperTypes.swift
closes #143 
Changes how the `AnyCodable` manages its internal representation, fixing a bug where it would fail to get the underlying type right after being instantiated.
Applies full `Equatable` conformance and adds a convenience `stringRepresentation` to help visualize the type on console prints.
Also, improves the public API documentation.
=> #143 AnyCodable fix & improvement

Sources/WalletConnect/Engine/PairingEngine.swift, Sources/WalletConnect/Engine/SessionEngine.swift, Sources/WalletConnect/Engine/SessionStateMachines/ControllerSessionStateMachine.swift, Sources/WalletConnect/Engine/SessionStateMachines/NonControllerSessionStateMachine.swift, Sources/WalletConnect/Engine/SessionStateMachines/SessionStateMachineValidating.swift, Sources/WalletConnect/Types/Pairing/PairingSequence.swift, Sources/WalletConnect/Types/Pairing/PairingType.swift, Sources/WalletConnect/Types/ReasonCode.swift, Sources/WalletConnect/Types/Session/SessionSequence.swift, Sources/WalletConnect/Types/WCMethod.swift, Sources/WalletConnect/WalletConnectClient.swift, Sources/WalletConnect/WalletConnectClientDelegate.swift, Sources/WalletConnect/WalletConnectError.swift, Sources/WalletConnectKMS/Crypto/KeyManagementService.swift, Sources/WalletConnectUtils/TimeInterval+Extension.swift, Tests/WalletConnectTests/ControllerSessionStateMachineTests.swift, Tests/WalletConnectTests/Helpers/Error+Extension.swift, Tests/WalletConnectTests/Mocks/MockedRelay.swift, Tests/WalletConnectTests/NonControllerSessionStateMachineTests.swift, Tests/WalletConnectTests/PairingEngineTests.swift, Tests/WalletConnectTests/PairingSequenceTests.swift, Tests/WalletConnectTests/SessionEngineTests.swift, Tests/WalletConnectTests/Stub/Stubs.swift
- Add tests for pairing expiry dates and updates.
- Replaces legacy factory method from when a pairing had multiple sub-states.
- Binds extended expiry with activation.
=> #18 Pairing expiry tests

Example/ExampleApp/Wallet/WalletViewController.swift, Sources/WalletConnect/Engine/PairingEngine.swift, Sources/WalletConnect/Engine/SessionEngine.swift, Sources/WalletConnect/Engine/SessionStateMachines/SessionStateMachineValidating.swift, Sources/WalletConnect/Namespace.swift, Sources/WalletConnect/NetworkInteractor/NetworkInteractor.swift, Sources/WalletConnect/Request.swift, Sources/WalletConnect/Types/Session/SessionType.swift, Sources/WalletConnect/Types/Session/WCSession.swift, Sources/WalletConnect/WalletConnectClient.swift, Sources/WalletConnect/WalletConnectError.swift, Tests/IntegrationTests/ClientTest.swift, Tests/WalletConnectTests/SessionEngineTests.swift, Tests/WalletConnectTests/Stub/Stubs.swift
closes #201
Makes `chainId` a required parameter in request and event payloads.
=> #201 required chainid

Example/DApp/SceneDelegate.swift, Example/ExampleApp/Wallet/WalletViewController.swift, Sources/WalletConnectAuth/Auth/Auth.swift, Sources/WalletConnectAuth/Auth/AuthClient.swift, Sources/WalletConnectAuth/Engine/Common/SessionEngine.swift, Sources/WalletConnectAuth/Storage/SessionStorage.swift, Tests/WalletConnectTests/ControllerSessionStateMachineTests.swift, Tests/WalletConnectTests/Mocks/WCSessionStorageMock.swift, Tests/WalletConnectTests/NonControllerSessionStateMachineTests.swift, Tests/WalletConnectTests/SessionEngineTests.swift
- remove getAcknowledgedSessions() and return all sessions for getSessions() method
we cannot display only acknowledged sessions for wallet because if user have dapp in mobile browser and native swift wallet on session approval in wallet session won't get acknowledges as dapp is not able to respond in background.
=> remove getAcknowledgedSessions

Sources/Chat/Chat.swift, Sources/Chat/Engine.swift, Sources/Chat/NetworkingInteractor.swift, Sources/Chat/Registry.swift, Sources/Chat/RegistryManager.swift, Sources/Chat/Types/ChatError.swift, Sources/Chat/Types/ChatRequest.swift, Sources/Chat/Types/Invite.swift, Tests/ChatTests/EndToEndTests.swift, Tests/ChatTests/Mocks/NetworkingInteractorMock.swift, Tests/ChatTests/RegistryManagerTests.swift, Tests/WalletConnectSignTests/ApproveEngineTests.swift, Tests/WalletConnectSignTests/ControllerSessionStateMachineTests.swift, Tests/WalletConnectSignTests/Mocks/MockedRelay.swift, Tests/WalletConnectSignTests/NonControllerSessionStateMachineTests.swift, Tests/WalletConnectSignTests/PairEngineTests.swift, Tests/WalletConnectSignTests/PairingEngineTests.swift
- Add registry manager
- update client api with specs
- add Concurrency
=> #chat/registry

Sources/WalletConnectSign/Engine/Common/ApproveEngine.swift, Sources/WalletConnectSign/Namespace.swift, Sources/WalletConnectSign/Sign/SignClient.swift, Sources/WalletConnectUtils/KeyValueStorage.swift, Tests/IntegrationTests/ClientTest.swift, Tests/IntegrationTests/Helpers/Stubs.swift, Tests/IntegrationTests/SignClientTests.swift, Tests/TestingUtils/Mocks/KeychainServiceFake.swift
Re-enable the first test case of the integration tests target.
- Uncommented and cleaned proposal+approval integration test case.
- Change the priority of the `Task` in approval engine's `handleSessionProposeResponse` to `.background` to avoid deadlocking during the async test.
- Re-enable next test cases.
=> #250 Integration Tests: Re-enable session propose-approve test case

Example/ExampleApp/SessionDetails/SessionDetailViewController.swift, Example/ExampleApp/Wallet/WalletViewController.swift, Example/UITests/Engine/RoutingEngine.swift, Example/UITests/Regression/RegressionTests.swift, Sources/WalletConnectKMS/Serialiser/Serializer.swift, Sources/WalletConnectRelay/Dispatching.swift, Sources/WalletConnectRelay/RelayClient.swift, Sources/WalletConnectSign/Engine/Common/ApproveEngine.swift, Sources/WalletConnectSign/Engine/Common/SessionEngine.swift, Sources/WalletConnectSign/Engine/Controller/ControllerSessionStateMachine.swift, Sources/WalletConnectSign/Engine/NonController/NonControllerSessionStateMachine.swift, Sources/WalletConnectSign/JsonRpcHistory/JsonRpcHistory.swift, Sources/WalletConnectSign/Namespace.swift, Sources/WalletConnectSign/NetworkInteractor/NetworkInteractor.swift, Sources/WalletConnectSign/Sign/Sign.swift, Sources/WalletConnectSign/Sign/SignClient.swift, Sources/WalletConnectSign/Types/ReasonCode.swift, Sources/WalletConnectSign/WalletConnectError.swift, Sources/WalletConnectUtils/Extensions/String.swift, Sources/WalletConnectUtils/JsonRpcHistory.swift, Tests/IntegrationTests/SignClientTests.swift, Tests/RelayerTests/Mocks/DispatcherMock.swift, Tests/WalletConnectSignTests/ApproveEngineTests.swift, Tests/WalletConnectSignTests/BlockchainTests.swift, Tests/WalletConnectSignTests/Mocks/MockedRelay.swift, Tests/WalletConnectSignTests/NonControllerSessionStateMachineTests.swift
**What changed?**
**Sample app** 
Approve / Reject calls wrapped in Tasks. Errors handled by logger
**SDK**
- Async `Approve` and `Reject` methods
- `NetworkInteractor`: Async RespondError and RespondSuccess methods
- `Dispatcher`: Async Send method
- Async callbacks for `wcRequestPublisher` subscribers
- Respond Namespace validation errors
=> ApproveEngine async calls

Example/DApp/Connect/ConnectViewController.swift, Example/ExampleApp/Wallet/WalletViewController.swift, Sources/Chat/Types/ChatRequestParams.swift, Sources/WalletConnectSign/Engine/Common/ApproveEngine.swift, Sources/WalletConnectSign/Engine/Controller/ControllerSessionStateMachine.swift, Sources/WalletConnectSign/Engine/NonController/NonControllerSessionStateMachine.swift, Sources/WalletConnectSign/Namespace.swift, Sources/WalletConnectSign/NetworkInteractor/NetworkInteractor.swift, Sources/WalletConnectSign/Request.swift, Sources/WalletConnectSign/Storage/SequenceStore.swift, Sources/WalletConnectSign/Storage/SessionStorage.swift, Sources/WalletConnectSign/Subscription/WCRequestSubscriptionPayload.swift, Sources/WalletConnectSign/Types/Pairing/WCPairing.swift, Sources/WalletConnectSign/Types/Session/WCSession.swift, Sources/WalletConnectSign/Types/WCRequest.swift, Sources/WalletConnectSign/Types/WCResponse.swift, Sources/WalletConnectUtils/JSONRPC/JSONRPCRequest.swift, Sources/WalletConnectUtils/JSONRPC/JsonRpcResult.swift, Sources/WalletConnectUtils/JsonRecID.swift, Tests/WalletConnectSignTests/Mocks/WCSessionStorageMock.swift, Tests/WalletConnectSignTests/SequenceStoreTests.swift, Tests/WalletConnectSignTests/SessionStorageTests.swift, Tests/WalletConnectSignTests/Stub/Session+Stub.swift, Tests/WalletConnectSignTests/WCResponseTests.swift, Tests/WalletConnectSignTests/WCSessionTests.swift
**What changed**
- callbacks implemented in for `handleUpdateResponse` and `handleUpdateExpiryResponse`
- timestamp added to WCSession
- WCSession migration example (for timestamp)
- WCSessionStorage - isNeedToReplace logic
- ExpirableSequence renamed to SequenceObject
- SessionStorageTests
=> [Wallet] State synchronisation

Example/IntegrationTests/Relay/RelayClientEndToEndTests.swift, Sources/WalletConnectRelay/AsyncWebSocketProxy.swift, Sources/WalletConnectRelay/ClientAuth/AuthChallengeProvider.swift, Sources/WalletConnectRelay/ClientAuth/ClientIdStorage.swift, Sources/WalletConnectRelay/ClientAuth/DIDKeyFactory.swift, Sources/WalletConnectRelay/ClientAuth/SocketAuthenticator.swift, Sources/WalletConnectRelay/HTTP/HTTPClient.swift, Sources/WalletConnectRelay/HTTP/HTTPError.swift, Sources/WalletConnectRelay/HTTP/HTTPResponse.swift, Sources/WalletConnectRelay/RelayClient.swift, Sources/WalletConnectRelay/SocketConnectionHandler/AutomaticSocketConnectionHandler.swift, Sources/WalletConnectRelay/SocketConnectionHandler/SocketConnectionHandler.swift, Sources/WalletConnectRelay/SocketConnectionHandler/WebSocket.swift, Tests/IntegrationTests/AuthChallengeTests.swift, Tests/RelayerTests/AuthTests/ClientIdStorageTests.swift, Tests/RelayerTests/AuthTests/ED25519DIDKeyTests.swift, Tests/RelayerTests/AuthTests/SocketAuthenticatorTests.swift, Tests/RelayerTests/AutomaticSocketConnectionHandlerTests.swift, Tests/RelayerTests/DispatcherTests.swift, Tests/RelayerTests/HTTPResponseTests.swift, Tests/RelayerTests/Helpers/Error+Extension.swift, Tests/RelayerTests/Mocks/AuthChallengeProviderMock.swift, Tests/RelayerTests/Mocks/ED25519DIDKeyFactoryMock.swift, Tests/TestingUtils/HelperTypes.swift
closes #290 
- HTTP client added to relay package w/ completion & async methods. Session's standard `async` API requires iOS 15+
- Integrated `AuthChallengeProvider` call. Integration tested on dev API.
PS: It's ready, only needs to be instantiated in the SDK
=> Feature: #290 HTTP client & auth challenge call

Example/IntegrationTests/Relay/RelayClientEndToEndTests.swift, Sources/WalletConnectRelay/HTTP/HTTPClient.swift, Sources/WalletConnectRelay/RelayClient.swift, Sources/WalletConnectRelay/RelayJSONRPC.swift, Sources/WalletConnectSign/Sign/SignClient.swift, Sources/WalletConnectSign/Types/Pairing/WCPairing.swift, Tests/RelayerTests/IridiumRelayTests.swift, Tests/WalletConnectSignTests/Stub/Stubs.swift, Tests/WalletConnectSignTests/WCRelayTests.swift, Tests/WalletConnectSignTests/WalletConnectURITests.swift
**What changed?**
- waku methods renamed to iridium
- URI format changed
- validate only last part of subscription method
=> [Feature] Protocol renaming #272

Example/IntegrationTests/Relay/RelayClientEndToEndTests.swift, Sources/Chat/NetworkingInteractor.swift, Sources/WalletConnectRelay/PublishTag.swift, Sources/WalletConnectRelay/RelayClient.swift, Sources/WalletConnectRelay/RelayJSONRPC.swift, Sources/WalletConnectSign/NetworkInteractor/NetworkInteractor.swift, Sources/WalletConnectSign/NetworkInteractor/NetworkRelaying.swift, Tests/RelayerTests/IridiumRelayTests.swift, Tests/WalletConnectSignTests/Mocks/MockedRelayClient.swift
Adds the `tag` parameter to publish method payload, and to relay call hierarchy.
=> [Network] Feature: #297 Message Tag

Example/IntegrationTests/Sign/SignClientTests.swift
Re-enables session delete test.
=> [Tests] #250: Re-enable session delete integration test

Example/IntegrationTests/Chat/RegistryTests.swift, Example/Showcase/Classes/DomainLayer/Chat/ChatFactory.swift, Sources/Chat/ProtocolServices/Common/MessagingService.swift, Sources/Chat/Services/RegisterService.swift, Sources/Chat/Services/ResolveService.swift, Sources/WalletConnectRelay/HTTP/HTTPService.swift
**Bug description**
Message not displayed after sending
=> [Chat] Message callback on send

Sources/WalletConnectSign/Engine/Common/ApproveEngine.swift, Sources/WalletConnectSign/Namespace.swift, Sources/WalletConnectSign/Types/Session/WCSession.swift, Tests/WalletConnectSignTests/Stub/Session+Stub.swift, Tests/WalletConnectSignTests/WCSessionTests.swift
closes #340 
- Allows for the replacement of namespace accounts as long as it complies with the existing required namespace chains.
- `WCSession` required namespaces type changed to `ProposalNamespace`.
=> [Bugfix] #340: Required namespaces check

.github/workflows/swift.yml
* improvement: cancels obsolete PR runs
* Bug fix: currently `push` triggers might run in parallel and might lost context of which merge broke the build
Resolves #345 
Not tested (copied from other working examples)
=> feat: uses concurrency to cancel obsolete runs

.github/workflows/ci.yml
The UI test takes the longest so this is an attempt to start it first to decrease the total time.
Also renames the workflow to `ci`.
Not tested
=> feat: reorders the ci steps to decrease ci time

Sources/WalletConnectSign/Engine/Controller/PairEngine.swift
- fix crash on pair but does not override key in keychain close #248
- sync develop with main
=> #248 fix crash on pair

Sources/WalletConnectSign/Engine/Common/ApproveEngine.swift, Tests/WalletConnectSignTests/ApproveEngineTests.swift, Tests/WalletConnectSignTests/Stub/Stubs.swift
extend pairing on every approve proposal on wallet
=> #347 extend pairing on approve proposal

.swiftpm/xcode/xcshareddata/xcschemes/AuthTests.xcscheme, Example/IntegrationTests/Relay/RelayClientEndToEndTests.swift, Example/Showcase/Classes/PresentationLayer/Import/ImportInteractor.swift, Package.swift, Sources/Auth/AuthClient.swift, Sources/Auth/File.swift, Sources/Auth/Services/App/AuthRequestService.swift, Sources/Auth/Services/App/CreatePairingService.swift, Sources/Auth/Services/Wallet/AuthService.swift, Sources/Auth/Services/Wallet/PairService.swift, Sources/Auth/Types/AuthPayloadParams.swift, Sources/Auth/Types/Cacao/CacaoHeader.swift, Sources/Auth/Types/Cacao/CacaoPayload.swift, Sources/Auth/Types/Cacao/CacaoSignature.swift, Sources/Auth/Types/RelayProtocolOptions.swift, Sources/Auth/Types/RequestParams.swift, Sources/Auth/Types/RespondParams.swift, Sources/Auth/Types/WalletConnectURI.swift, Sources/WalletConnectSign/Types/Common/RelayProtocolOptions.swift, Sources/WalletConnectSign/Types/RelayProtocolOptions.swift, Sources/WalletConnectSign/Types/Session/WCSession.swift, Sources/WalletConnectUtils/RelayProtocolOptions.swift, Sources/WalletConnectUtils/WalletConnectURI.swift, Tests/AuthTests/AuthClientTest.swift, Tests/AuthTests/File.swift, Tests/RelayerTests/DispatcherTests.swift
=> #379 auth core types

.github/workflows/intake.yml
If a team member creates an issue it goes straight to the board, else it needs to be labeled as "accepted".
Tested in the monorepo and just copy/pasta here.
=> feat: moves issues to the Swift board

.github/actions/ci/action.yml, Sources/WalletConnectSign/Engine/Common/ApproveEngine.swift, Tests/AuthTests/Stubs/RequestSubscriptionPayload.swift, Tests/JSONRPCTests/Helpers.swift, Tests/JSONRPCTests/RPCRequestTests.swift, Tests/JSONRPCTests/RPCResponseTests.swift, Tests/TestingUtils/Helpers.swift, Tests/WalletConnectSignTests/Mocks/NetworkingInteractorMock.swift, Tests/WalletConnectSignTests/PairingEngineTests.swift, Tests/WalletConnectUtilsTests/RPCHistoryTests.swift
=> Fix unit test run

Example/ExampleApp/Wallet/WalletViewController.swift, Example/IntegrationTests/Sign/SignClientTests.swift, Sources/Auth/Services/Common/SIWEMessageFormatter.swift, Sources/Auth/Services/Wallet/AuthRequestSubscriber.swift, Sources/WalletConnectSign/Engine/Common/ApproveEngine.swift, Sources/WalletConnectSign/Engine/Common/SessionEngine.swift, Sources/WalletConnectSign/Engine/NonController/NonControllerSessionStateMachine.swift, Sources/WalletConnectSign/RejectionReason.swift, Sources/WalletConnectSign/Types/ReasonCode.swift, Tests/AuthTests/SIWEMessageFormatterTests.swift, Tests/WalletConnectSignTests/NonControllerSessionStateMachineTests.swift
update protocol codes to match specs
close #372
=> [Sign] #372 Clean protocol codes

Example/IntegrationTests/Sign/SignClientTests.swift, Sources/Auth/Services/App/AuthRequestService.swift, Sources/Auth/Services/App/AuthRespondSubscriber.swift, Sources/Auth/Services/Common/NetworkingInteractor.swift, Sources/Auth/Services/Common/SIWEMessageFormatter.swift, Sources/Auth/Services/Wallet/AuthRequestSubscriber.swift, Sources/Auth/Types/ResponseSubscriptionPayload.swift, Sources/WalletConnectSign/Engine/Common/ApproveEngine.swift, Sources/WalletConnectUtils/RPCHistory.swift, Tests/AuthTests/Mocks/NetworkingInteractorMock.swift, Tests/AuthTests/SIWEMessageFormatterTests.swift
Add `requestNetworkAck` function that completes with an acknowledgement from the relay network.
handles incoming requests and responses to networking interactor and publishes decrypted rpc requests to subscribers
=> #382 auth networking interactor

.github/workflows/intake.yml
The `JamesSingleton/is-organization-member@1.0.0` action we were using doesn't work for all WalletConnect org members as some don't display their membership publicy and the action doesn't support that.
Sample run: https://github.com/WalletConnect/WalletConnectSwiftV2/actions/runs/2803435983
=> fix: intake process does not work for non-public org members

Example/DApp/SelectChain/SelectChainView.swift, Example/DApp/SelectChain/SelectChainViewController.swift, Example/ExampleApp.xcodeproj/project.pbxproj, Example/ExampleApp/Wallet/WalletViewController.swift, Package.swift, Sources/WalletConnectRouter/Router.m, Sources/WalletConnectRouter/include/Router.h, Sources/WalletConnectRouter/include/module.modulemap
close #233
**What changed**
WalletConnectRouter wrap `goBack()` action for external usage. Usage example added in sample app
**Sample app**
https://user-images.githubusercontent.com/5384197/183735032-52394713-e7ab-4981-ae64-4171151a7ac6.mov
=> [Core] WalletConnectRouter

Example/ExampleApp.xcodeproj/project.pbxproj, Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.swift, Sources/Auth/Services/Signer/Signer.swift, Tests/AuthTests/CacaoSignerTests.swift, Tests/AuthTests/SignerTests.swift
***What changed***
Replay protection implemented
=> [Hotfix] EIP-155 signature fix

Tests/WalletConnectSignTests/WCPairingTests.swift
- Rename some tests to specify if is testing init from uri or topic 
- Add scenarios that throw error 
While working on this I noticed that the `activate` function sets the status to `true` even if `updateExpiry` throws an [error](https://github.com/WalletConnect/WalletConnectSwiftV2/blob/b676369f6dd72d8d0d80fe1275313f1f74cade7b/Sources/WalletConnectPairing/Types/WCPairing.swift#L52). Is that the expected behavior? Maybe `activate` should only change the `active` var?
=> Adds more unit tests for WCPairing

Sources/WalletConnectRelay/SocketConnectionHandler/AutomaticSocketConnectionHandler.swift, Sources/WalletConnectRelay/SocketConnectionHandler/BackgroundTaskRegistering.swift, Tests/RelayerTests/Mocks/BackgroundTaskRegistrarMock.swift
Invalidates background tasks when app is entering foreground
Resolves #456
=> [Relay] Add invalidation of background task

Example/IntegrationTests/Auth/AuthTests.swift, Sources/Auth/AuthClient.swift, Sources/Auth/Services/App/AppRespondSubscriber.swift, Sources/Auth/Services/Signer/MessageSigner.swift, Sources/Auth/Services/Signer/Signer.swift, Sources/Auth/Services/Wallet/WalletRespondService.swift, Sources/Auth/Types/Cacao/CacaoSignature.swift, Sources/Auth/Types/Errors/AuthError.swift, Sources/Auth/Types/RespondParams.swift
- handle peer error response 
- add testUserRespondError
- add reject method to public interface
Resolves #459 #460
- integration tests
=> [Auth] Test respond error

Sources/WalletConnectUtils/WalletConnectURI.swift, Tests/WalletConnectUtilsTests/WalletConnectURITests.swift
Updates `WalletConnectURI` to include a API prefix in its format. Implementation is backwards compatible with legacy format.
Resolves #454 
Unit tests
=> #454 Update `WalletConnectURI` with API identifier prefix

Example/DApp/Auth/AuthView.swift, Example/DApp/Auth/AuthViewModel.swift, Example/DApp/SceneDelegate.swift, Example/IntegrationTests/Auth/AuthTests.swift, Example/Showcase/Classes/ApplicationLayer/SceneDelegate.swift, Example/Showcase/Classes/PresentationLayer/Wallet/Scan/Views/ScanQR.swift, Example/Showcase/Classes/PresentationLayer/Wallet/Scan/Views/ScanQRView.swift, Package.swift, Sources/Auth/Auth.swift, Sources/Auth/AuthClient.swift, Sources/Auth/AuthClientFactory.swift, Sources/Auth/Services/App/AppRespondSubscriber.swift, Sources/Auth/Services/Common/NetworkingInteractor.swift, Sources/Auth/Types/Errors/Reason.swift, Sources/WalletConnectSign/Sign/SignClient.swift, Tests/AuthTests/AppRespondSubscriberTests.swift, Tests/AuthTests/Mocks/AppMetadata.swift, Tests/AuthTests/Mocks/NetworkingInteractorMock.swift, Tests/RelayerTests/Mocks/BackgroundTaskRegistrarMock.swift, Tests/TestingUtils/Mocks/WCPairingStorageMock.swift, Tests/WalletConnectSignTests/Mocks/AppMetadata.swift, Tests/WalletConnectSignTests/Stub/Stubs.swift, Tests/WalletConnectSignTests/WCPairingTests.swift
Extend pairing on app from 5minutes to 30days after response from wallet is received. Extension happens on every response.
Resolves #472 
manually
=> [Auth] #472 extend pairing

Example/DApp/Auth/AuthView.swift, Example/DApp/Auth/AuthViewModel.swift, Example/DApp/SceneDelegate.swift, Example/DApp/Sign/Connect/ConnectViewController.swift, Example/DApp/Sign/SelectChain/SelectChainViewController.swift, Example/ExampleApp/SceneDelegate.swift, Example/ExampleApp/Wallet/WalletViewController.swift, Example/IntegrationTests/Auth/AuthTests.swift, Example/Showcase/Classes/ApplicationLayer/SceneDelegate.swift, Example/Showcase/Classes/PresentationLayer/Wallet/Scan/Views/ScanQR.swift, Example/Showcase/Classes/PresentationLayer/Wallet/Scan/Views/ScanQRView.swift, Sources/Auth/Auth.swift, Sources/Auth/AuthClient.swift, Sources/Auth/Services/App/AppPairService.swift, Sources/Auth/Services/Common/NetworkingInteractor.swift, Sources/Auth/Types/Aliases/WalletConnectURI.swift, Sources/Auth/Types/Errors/Reason.swift, Sources/WalletConnectSign/Sign/SignClient.swift, Sources/WalletConnectSign/Types/WalletConnectURI.swift, Sources/WalletConnectSign/WalletConnectError.swift, Sources/WalletConnectUtils/WalletConnectURI.swift, Tests/AuthTests/Mocks/AppMetadata.swift, Tests/AuthTests/Mocks/NetworkingInteractorMock.swift, Tests/RelayerTests/Mocks/BackgroundTaskRegistrarMock.swift, Tests/WalletConnectSignTests/Mocks/AppMetadata.swift, Tests/WalletConnectSignTests/Stub/Stubs.swift, Tests/WalletConnectSignTests/WCPairingTests.swift
- String replaced with WalletConnectURI
- Lint
Resolves #465
Run UI tests
=> [Interface] Replace string with WalletConnectURI

Sources/Auth/Services/App/AppRespondSubscriber.swift, Sources/Auth/Services/Wallet/WalletRespondService.swift, Sources/Auth/Types/Cacao/Cacao.swift, Sources/Auth/Types/ProtocolRPCParams/AuthResponseParams.swift, Tests/AuthTests/AppRespondSubscriberTests.swift
- manual tests with kotlin sdk
=> Rename cacao params

Sources/Auth/AuthClient.swift, Sources/Auth/AuthClientFactory.swift, Sources/Auth/Services/Common/PairingsProvider.swift, Sources/Auth/Types/Aliases/Pairing.swift, Sources/WalletConnectPairing/Types/Pairing.swift, Sources/WalletConnectSign/Types/Aliases/Pairing.swift
exposes getPairings() method on auth client api
=> #488 get pairings

Example/ExampleApp/SceneDelegate.swift, Example/IntegrationTests/Relay/RelayClientEndToEndTests.swift, Sources/WalletConnectRelay/RelayClient.swift, Sources/WalletConnectSign/Sign/SignClientFactory.swift
- hot fix for json rpc duplicates
relay client was not acknowledging subscription requests to the relay server.
- fix issue with handling deep link by sample wallet when socket is connected
manual testing and integration testing
=> [Relay] Fot fix for json rpc duplicates 

Example/ExampleApp/SceneDelegate.swift, Sources/WalletConnectRelay/Dispatching.swift, Sources/WalletConnectRelay/RelayClient.swift, Tests/RelayerTests/DispatcherTests.swift, Tests/RelayerTests/Mocks/DispatcherMock.swift
=> [Relay] Retry on connection error

Example/IntegrationTests/Auth/AuthTests.swift, Example/IntegrationTests/Chat/ChatTests.swift, Example/IntegrationTests/Sign/SignClientTests.swift, Sources/WalletConnectRelay/Dispatching.swift
- Fixed Dispatcher retry bug 
- Connection helpers removed from all integration tests
=> [Bugfix] Combine timeout for dispatcher retry

.github/actions/ci/action.yml, .github/workflows/ci.yml, .gitignore, Configuration.xcconfig, Example/DApp/Common/InputConfig.swift, Example/DApp/Info.plist, Example/DApp/SceneDelegate.swift, Example/ExampleApp.xcodeproj/project.pbxproj, Example/ExampleApp.xcodeproj/xcshareddata/xcschemes/IntegrationTests.xcscheme, Example/ExampleApp/Common/InputConfig.swift, Example/ExampleApp/Info.plist, Example/ExampleApp/SceneDelegate.swift, Example/IntegrationTests/Auth/AuthTests.swift, Example/IntegrationTests/Chat/ChatTests.swift, Example/IntegrationTests/Pairing/PairingTests.swift, Example/IntegrationTests/Relay/RelayClientEndToEndTests.swift, Example/IntegrationTests/Sign/SignClientTests.swift, Example/IntegrationTests/Stubs/InputConfig.swift, Example/Showcase/Classes/ApplicationLayer/Configurator/ThirdPartyConfigurator.swift, Example/Showcase/Common/InputConfig.swift, Example/Showcase/Other/Info.plist, README.md
=> [CI] Project ID from secrets

Sources/WalletConnectPairing/Types/AppMetadata.swift
- AppMetadata redirect property
- Redirect setting nil by default to keep backward compatibility
=> AppMetadata redirect

Example/DApp/Auth/AuthCoordinator.swift, Example/DApp/Sign/Connect/ConnectViewController.swift, Example/DApp/Sign/SelectChain/SelectChainViewController.swift, Example/ExampleApp/SceneDelegate.swift, Example/ExampleApp/Wallet/WalletViewController.swift, Example/IntegrationTests/Sign/SignClientTests.swift, Sources/Auth/Auth.swift, Sources/WalletConnectPairing/Pair.swift, Sources/WalletConnectPairing/PairingClient.swift, Sources/WalletConnectPairing/PairingInteracting.swift, Sources/WalletConnectPairing/Services/Common/CleanupService.swift, Sources/WalletConnectSign/Services/DisconnectService.swift, Sources/WalletConnectSign/Sign/Sign.swift, Sources/WalletConnectSign/Sign/SignClient.swift, Sources/WalletConnectSign/Sign/SignClientFactory.swift
Integrates Pairing AIP into wallet and a dapp
=> [Apps] Wallet pairing integration

.github/actions/ci/action.yml, .github/workflows/ci.yml, Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
=> [CI] Derived data cache

Example/IntegrationTests/Chat/ChatTests.swift, Example/Showcase/Classes/DomainLayer/Chat/ChatService.swift, Example/Showcase/Classes/PresentationLayer/Chat/Invite/InviteInteractor.swift, Sources/Chat/ChatClient.swift, Sources/Chat/ChatClientFactory.swift, Sources/Chat/ProtocolServices/Inviter/InviteService.swift
Invite method updated according specs 
=> [Chat] PubKey removed from invite

Sources/Commons/AnyCodable.swift, Sources/Commons/AnyCodableError.swift, Tests/CommonsTests/AnyCodableTests.swift
Connected with Solana transaction signing issue:
https://walletconnect.slack.com/archives/C03T13E862C/p1667311895685149?thread_ts=1666277183.270559&cid=C03T13E862C
=> [Core] AnyCodable null decoding

Sources/WalletConnectSign/Engine/Common/ApproveEngine.swift
Add concurrency for settle request and propose response
Speeds up sign integration tests execution by ~0.7s on local mac
Resolves #575
=> [Sign] #575 concurrent settle request and propose response

Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Sources/JSONRPC/RPCResponse.swift, Sources/WalletConnectSign/Engine/Common/SessionEngine.swift, Tests/JSONRPCTests/RPCResponseTests.swift
Errors were responded as `RPCResponse.result` instead of  `RPCResponse.error`
=> [Sign] Response error fix

Sources/WalletConnectRelay/AppStateObserving.swift, Sources/WalletConnectRelay/Dispatching.swift, Sources/WalletConnectRelay/NetworkMonitoring.swift, Sources/WalletConnectRelay/SocketConnectionHandler/AutomaticSocketConnectionHandler.swift, Sources/WalletConnectRelay/SocketConnectionHandler/ManualSocketConnectionHandler.swift, Sources/WalletConnectRelay/SocketConnectionHandler/SocketConnectionHandler.swift, Tests/RelayerTests/AutomaticSocketConnectionHandlerTests.swift, Tests/RelayerTests/Mocks/AppStateObserverMock.swift
AutomaticConnectionHandler: 
- reconnect on every disconnect in foreground
ManualConnectionHandler: 
- no reconnections
Resolves  #576
=> [Relay] Socket reconnection

Example/ExampleApp/SceneDelegate.swift, Sources/WalletConnectNetworking/NetworkInteracting.swift, Sources/WalletConnectNetworking/NetworkingInteractor.swift, Sources/WalletConnectRelay/RelayClient.swift, Sources/WalletConnectSign/Services/SignCleanupService.swift, Sources/WalletConnectSign/Sign/SignClient.swift, Sources/WalletConnectSign/Sign/SignClientFactory.swift, Sources/WalletConnectUtils/RPCHistory/RPCHistory.swift, Tests/TestingUtils/NetworkingInteractorMock.swift
- cleanup method opened
- batch unsubscribe method implemented
Resolves #614, #627
=> [Sign] Cleanup method opened

Example/ExampleApp.xcodeproj/project.pbxproj, Example/ExampleApp/AppDelegate.swift, Example/IntegrationTests/Push/PushTests.swift, Sources/WalletConnectEcho/Echo.swift, Sources/WalletConnectEcho/Register/EchoRegisterService.swift, Sources/WalletConnectPush/Client/Wallet/WalletPushClient.swift, Sources/WalletConnectPush/Push.swift, Sources/WalletConnectPush/PushConfig.swift
add push config in order to not require from sdk consumer configuration of Echo 
manual testing with Example App
=> [Push] configure echo over push config

WalletConnectSwiftV2.podspec
Cocoapods warnings fixed. More: https://github.com/WalletConnect/WalletConnectSwiftV2/pull/670
=> [Cocoapods] source_files file extensions

.swiftpm/xcode/xcshareddata/xcschemes/WalletConnectSignTests.xcscheme, Example/IntegrationTests/Sign/SignClientTests.swift, Sources/WalletConnectSign/Engine/Common/SessionEngine.swift, Sources/WalletConnectSign/Request.swift, Sources/WalletConnectSign/Services/HistoryService.swift, Sources/WalletConnectSign/Sign/SignClient.swift, Sources/WalletConnectSign/Sign/SignClientFactory.swift, Sources/WalletConnectSign/Types/ProtocolMethods/SessionRequestProtocolMethod.swift, Sources/WalletConnectSign/Types/Session/SessionType.swift, Sources/WalletConnectSign/Types/SignReasonCode.swift, Tests/TestingUtils/NetworkingInteractorMock.swift, Tests/WalletConnectSignTests/SessionEngineTests.swift, Tests/WalletConnectSignTests/SessionRequestTests.swift, Tests/WalletConnectSignTests/Stub/Stubs.swift
=> [Sign] Session request expiry

Example/IntegrationTests/Relay/RelayClientEndToEndTests.swift
The problem description is in the thread - https://walletconnect.slack.com/archives/C03S6NN8NHF/p1675357050503549
_The value used for the topic is randomly generated_
=> [CI] Make test topic value compliant with new relay topic policies

.github/workflows/release.yml, Makefile, fastlane/Fastfile
- include_all certificates
- project_id and host_url params
=> [CI] Include all certificates

Sources/WalletConnectSign/Engine/Common/SessionEngine.swift
Based on the OpenSea research:
The RPCRequest constructor in the SessionEngine is regenerating the id.
=> Pass request.id to the RPCRequest

Sources/WalletConnectPairing/PairingClientProtocol.swift, Sources/Web3Wallet/Web3WalletClient.swift, Tests/Web3WalletTests/Mocks/PairingClientMock.swift, Tests/Web3WalletTests/Web3WalletTests.swift
=> Web3Wallet expose disconnect pairing

Sources/WalletConnectPairing/PairingClientProtocol.swift, Sources/WalletConnectSign/Sign/SignClientProtocol.swift, Sources/Web3Wallet/Web3WalletClient.swift, Tests/Web3WalletTests/Mocks/PairingClientMock.swift, Tests/Web3WalletTests/Mocks/ReasonMock.swift, Tests/Web3WalletTests/Mocks/SignClientMock.swift, Tests/Web3WalletTests/Web3WalletTests.swift
Related to the [topic](https://walletconnect.slack.com/archives/C03T13E862C/p1676732936891759?thread_ts=1675969575.182249&cid=C03T13E862C):
```
Hey guys, related to Web3Wallet on iOS.
There are a lot of methods/combine publishers that we're currently using (From Sign and Pair targets) but they are not included in the Web3Wallet target and we need to import the other packages in order to make it work
Can we include them in the new SDK?
Sign
socketConnectionStatusPublisher
sessionSettlePublisher
sessionDeletePublisher
sessionResponsePublisher
cleanup
Pair
getPairings()
```
=> Expose new methods to web3wallet

Sources/WalletConnectUtils/Extensions/String+CAIPs.swift, Tests/WalletConnectUtilsTests/String+ExtensionTests.swift
CAIP-10 Regex updated with https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-10.md#syntax
Resolves https://github.com/WalletConnect/WalletConnectSwiftV2/pull/761
=> [Core] CAIP-10 regex fixed

Sources/WalletConnectEcho/Echo.swift, Sources/WalletConnectEcho/EchoClient.swift, Sources/WalletConnectEcho/EchoClientFactory.swift, Sources/WalletConnectEcho/EchoImports.swift, Sources/WalletConnectEcho/Register/EchoAuthPayload.swift, Sources/WalletConnectEcho/Register/EchoAuthenticator.swift, Sources/WalletConnectEcho/Register/EchoRegisterService.swift, Sources/WalletConnectEcho/Register/EchoService.swift, WalletConnectSwiftV2.podspec
=> [Cocoapods] Echo

Example/RelayIntegrationTests/RelayClientEndToEndTests.swift, Sources/WalletConnectRelay/Dispatching.swift, Sources/WalletConnectRelay/RelayClient.swift, Sources/WalletConnectRelay/RelayURLFactory.swift, Tests/RelayerTests/DispatcherTests.swift
=> [Relay] Regenerate socket URL on error disconnection

Configuration.xcconfig, Example/WalletApp/PresentationLayer/Wallet/SessionProposal/SessionProposalInteractor.swift, Sources/WalletConnectSign/Namespace.swift
=> Extend chains and methods

Package.swift, Sources/Web3Modal/Helpers/UIApplicationWrapper.swift, Sources/Web3Modal/Modal/ModalContainerView.swift, Sources/Web3Modal/Modal/ModalInteractor.swift, Sources/Web3Modal/Modal/ModalSheet+Previews.swift, Sources/Web3Modal/Modal/ModalSheet.swift, Sources/Web3Modal/Modal/ModalViewModel.swift, Tests/Web3ModalTests/Helpers/FuncTests.swift, Tests/Web3ModalTests/Mocks/ModalSheetInteractorMock.swift, Tests/Web3ModalTests/ModalViewModelTests.swift
Adds deeplink capability to wallets show in first screen
Added unit tests to verify encoding of URL to be opened as deeplink
=> [W3M] Deeplinking to wallets

.github/workflows/ci_v2.yml
More context here: https://iterative.ai/blog/testing-external-contributions-using-github-actions-secrets
NB: This is complicated to test as it needs to be merged in `main` first, so it is split in two parts leaving original `ci` workflow unchanged
=> [CI&CD] Fix CI runs for PRs from forks

Example/DApp/Sign/Connect/ConnectViewController.swift, Example/ExampleApp.xcodeproj/project.pbxproj, Example/WalletApp/ApplicationLayer/SceneDelegate.swift, Example/WalletApp/Common/Helpers/QueryParameters.swift
* added uri percent encoding in dapp. This is necessary in order to parse universal link with wallet connect pairing uri parameter in real applications. Pairing uri contains extra '?' which fails normal query parameters parsing.
* improved pairing uri parsing in WalletApp with query parameters handling.
It resolves inability to send correct pairing uri via universal link on iOS.
* you can try to connect dapp without percent encoding to any mobile wallet (e.g. TrustWallet)
* repeat it with percent encoding
=> [DApp, WalletApp] add uri encoding

Sources/WalletConnectNetworking/NetworkingInteractor.swift
In `NetworkingInteractor` `func respond(topic, response, protocolMethod, envelopeType)` is marked with `throws`, but there was still `try!` which would sometimes fail and crash the app, since method is marked with throws there should be no need to crash the app if try fails with `WalletConnectKMS.Serializer.Errors.symmetricKeyForTopicNotFound` error
=> Switch try! for try in NetworkingInteractor respond method

.github/workflows/cd.yml, .github/workflows/cocoapods.yml
- Lint only on release PR's
- Publish cocoapods on GH release
=> [CI] Publish cocoapods on GH release only

Example/IntegrationTests/Push/PushTests.swift, Sources/WalletConnectPush/Client/Wallet/PushMessagesDatabase.swift, Sources/WalletConnectUtils/Encodable.swift, Sources/Web3Inbox/WebView/WebViewProxy.swift
- fix date encoding strategy for web3inbox
- fix push test that was failing in rare cases blocking CI releases
Resolves #888
=> #888 w3i date encoding

Example/RelayIntegrationTests/RelayClientEndToEndTests.swift
The RelayClientEndToEndTests testEndToEndPayload fails sometimes on the CI. This is potential fix for the test, the change prevents clients from publishing duplicated messages and double subscribe for topic. It also adds 1s delay between A and B publish, simulating more real world scenerio.
=> fix testEndToEndPayload

Example/IntegrationTests/Auth/AuthTests.swift, Example/IntegrationTests/Chat/ChatTests.swift, Example/IntegrationTests/History/HistoryTests.swift, Example/IntegrationTests/Pairing/PairingTests.swift, Example/IntegrationTests/Push/PushTests.swift, Example/IntegrationTests/Sign/SignClientTests.swift, Example/IntegrationTests/Sync/SyncTests.swift, Example/RelayIntegrationTests/RelayClientEndToEndTests.swift, Sources/WalletConnectRelay/Relay.swift, Sources/WalletConnectRelay/RelayClient.swift, Sources/WalletConnectRelay/RelayClientFactory.swift, Tests/RelayerTests/RelayClientTests.swift
=> [Core] Add Relay Client factory

.github/workflows/deploy_pages.yml, Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.resolved, Package.swift, Sources/Web3Inbox/WebView/WebViewFactory.swift, generate_docs.sh
On push to `main` branch `deploy_pages.yml` workflow is going to be run. Executing the `generate_docs.sh` and then triggers deployment of github pages, deploying static site generated in `docs` directory
generate_docs.sh:
Runs `swift package  generate-documentation` for each target defined in `Package.swift`. Currently there is no support for multiple targets so we are storing produces files in temporary folders and merging these folders in next steps, including generating root `index.html` allowing to navigate to docs for individual targets as seen here 
https://walletconnect.github.io/WalletConnectSwiftV2/
Specific target documentation can be the found on following url
`https://walletconnect.github.io/WalletConnectSwiftV2/documentation/${ TARGET_NAME.allLowerCased }` e.g. …
=> [Docs] Generate and Deploy DocC to GH pages

.github/actions/run_tests_without_building/action.yml, .github/workflows/ci.yml, Configuration.xcconfig, Example/ExampleApp.xcodeproj/IntegrationTests.xctestplan, Example/IntegrationTests/Push/Publisher.swift, Example/Shared/Tests/InputConfig.swift, Makefile, NotifyTests.xctestplan
Add authorization header for /notify endpoint in push tests
=> [CI/Push] Notify server authentication

Sources/WalletConnectModal/Modal/ModalViewModel.swift, Sources/WalletConnectModal/Modal/RecentWalletStorage.swift, Sources/WalletConnectModal/Modal/Screens/WalletList.swift, Sources/WalletConnectModal/Networking/Explorer/ListingsResponse.swift
Store the time when user last time interacted with wallet and later use this information to show "Recent" wallets on top of the list
=> [WCM] Store recent wallets in UserDefaults

.github/workflows/ci.yml, .github/workflows/self_hosted_ci.yml, .swiftpm/xcode/xcshareddata/xcschemes/WalletConnect-Package.xcscheme, Example/ExampleApp.xcodeproj/project.pbxproj, Example/WalletConnect-Package.xctestplan, Makefile, Tests/WalletConnectModalTests/ModalViewModelTests.swift, run_tests.sh
=> [CI] Update ci.yml to use "self-hosted" m1 runner

.github/actions/build/action.yml, .github/workflows/ci.yml, .github/workflows/self_hosted_ci.yml
Guaranteeing that each pipeline uses the correct cache and no race condition is happening.
This fixes the issue when running two pipelines at the same time and the first which finishes the `prepare` step saves compiled artefacts into a cache, but due to using different archs (ARM/x86) it causes other pipeline to fail. 
It's a temporary solution which will be removed.
=> [CI] Use unique cache key for each workflow

Sources/WalletConnectNotify/ProtocolMethods/NotifySubscribeProtocolMethod.swift
As per the specs here: https://github.com/WalletConnect/walletconnect-docs/blob/main/docs/specs/clients/notify/rpc-methods.md?plain=1
Updating the Tags for Subscribe
=> Update NotifySubscribeProtocolMethod.swift to match specs

Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Sources/WalletConnectNotify/Client/Wallet/Extensions/NotificationCenter.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyClient.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyClientFactory.swift, Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyWatchSubscriptions/NotifyWatchSubscriptionsRequester.swift, Sources/WalletConnectNotify/Client/Wallet/SubscriptionWatcher.swift, Tests/NotifyTests/SubscriptionWatcherTests.swift
- Triggers notify watch subscription request every 5 minutes
- Sets up timer 
- manually
- unit tests
=> [Notify] Subscriptions watcher

Example/WalletApp/ApplicationLayer/ConfigurationService.swift, Example/WalletApp/ApplicationLayer/ProfilingService.swift, Sources/WalletConnectKMS/Keychain/KeychainError.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyClient.swift, Sources/WalletConnectPush/PushClient.swift, Sources/WalletConnectPush/PushClientFactory.swift, Sources/WalletConnectPush/Register/PushRegisterService.swift, Sources/WalletConnectUtils/Logger/Log.swift
=> [KMS] KeychainError description

Sources/WalletConnectNotify/Client/Wallet/NotifyClient.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyIdentityService.swift, Sources/WalletConnectNotify/Types/JWTPayloads/notify_watch_subscriptions/NotifyWatchSubscriptionsPayload.swift, Sources/Web3Inbox/NotifyClientProxy/NotifyClientProxy.swift
- siwe message updated according specs 
- encoding null app for watch subscription request jwt
=> [Notify] SIWE Spec change

Example/IntegrationTests/Push/NotifyTests.swift, Example/WalletApp/PresentationLayer/Wallet/Notifications/NotificationsInteractor.swift, Example/WalletApp/PresentationLayer/Wallet/Settings/SettingsInteractor.swift, Example/WalletApp/PresentationLayer/Wallet/Settings/SettingsPresenter.swift, Example/WalletApp/PresentationLayer/Wallet/Settings/SettingsRouter.swift, Example/WalletApp/PresentationLayer/Wallet/Settings/SettingsView.swift, Sources/Chat/ChatClient.swift, Sources/WalletConnectIdentity/IdentityClient.swift, Sources/WalletConnectIdentity/IdentityService.swift, Sources/WalletConnectKMS/Crypto/KeyManagementService.swift, Sources/WalletConnectNotify/Client/Wallet/Extensions/Array.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyAccountProvider.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyClient.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyClientFactory.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyIdentityService.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyResubscribeService.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyStorage.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyWatchAgreementService.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyWatcherAgreementKeysProvider.swift, Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifySubscriptionsChanged/NotifySubscriptionsChangedRequestSubscriber.swift, Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyWatchSubscriptions/NotifyWatchSubscriptionsRequester.swift, Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyWatchSubscriptions/NotifyWatchSubscriptionsResponseSubscriber.swift, Sources/WalletConnectNotify/Client/Wallet/SubscriptionWatcher.swift, Sources/WalletConnectNotify/Client/Wallet/SubscriptionsAutoUpdater.swift, Tests/NotifyTests/Mocks/MockNotifyStoring.swift, Tests/NotifyTests/SubscriptionWatcherTests.swift, Tests/TestingUtils/Mocks/KeyManagementServiceMock.swift
Spcs: https://github.com/WalletConnect/walletconnect-specs/pull/146
=> [Notify] Unregister method

Sources/WalletConnectSign/Sign/SignClientProtocol.swift, Tests/Web3WalletTests/Mocks/SignClientMock.swift
Web3Modal needs to listen for the "chainChanged" event so that it can reflect the chain switch accordingly.
=> [Sign] Expose session event publisher

Sources/WalletConnectKMS/Crypto/KeyManagementService.swift, Sources/WalletConnectKMS/Keychain/KeychainError.swift, Sources/WalletConnectKMS/Keychain/KeychainStorage.swift, Sources/WalletConnectRelay/ClientAuth/ClientIdStorage.swift
tryMigrateAttrAccessible: 
- Check if Migration needed
- Fetching old value
- Deleting old value
- Replacing with new value
=> [Core] Keychain migration

Sources/WalletConnectKMS/Keychain/KeychainStorage.swift
=> [Core] Update method migration

.swiftpm/xcode/xcshareddata/xcschemes/Database.xcscheme, Example/IntegrationTests/Push/NotifyTests.swift, Example/WalletApp/ApplicationLayer/LoggingService.swift, Package.swift, Sources/Database/DiskSqlite.swift, Sources/Database/MemorySqlite.swift, Sources/Database/SQLiteQuery.swift, Sources/Database/Sqlite.swift, Sources/Database/SqliteError.swift, Sources/Database/SqliteRow.swift, Sources/Database/SqliteRowDecoder.swift, Sources/Database/SqliteRowEncoder.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyAccountProvider.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyClient.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyClientFactory.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyDatabase.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyMessageRecord.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyStorage.swift, Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyDelete/DeleteNotifySubscriptionRequester.swift, Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyMessage/NotifyMessageSubscriber.swift, Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifySubscriptionsChanged/NotifySubscriptionsChangedRequestSubscriber.swift, Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyUpdate/NotifyUpdateRequester.swift, Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyWatchSubscriptions/NotifyWatchSubscriptionsResponseSubscriber.swift, Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_pushSubscribe/NotifySubscribeRequester.swift, Sources/WalletConnectNotify/NotifyImports.swift, Sources/WalletConnectNotify/NotifyStorageIdntifiers.swift, Sources/WalletConnectNotify/Types/DataStructures/NotifyMessage.swift, Sources/WalletConnectNotify/Types/DataStructures/NotifySubscription.swift, Tests/NotifyTests/Mocks/MockNotifyStoring.swift
=> [Notify] SQLite database for subscriptions and messages

Example/IntegrationTests/Push/NotifyTests.swift, Example/WalletApp/PresentationLayer/Wallet/Notifications/NotificationsInteractor.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyClient.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyStorage.swift, Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyMessage/NotifyMessageSubscriber.swift
=> [Notify] Client publishers updated

Example/IntegrationTests/Push/NotifyTests.swift
=> [Notify] Integration tests refactor

Package.swift, Sources/Database/DatabaseImports.swift, Sources/Database/DiskSqlite.swift, Sources/WalletConnectUtils/UnfairLock.swift
=> [Notify] Sqlite lock

Example/IntegrationTests/Push/NotifyTests.swift, Example/PNDecryptionService/NotificationService.swift, Example/WalletApp/ApplicationLayer/SceneDelegate.swift, Example/WalletApp/Other/Info.plist
=> [Sample] Notify notification tap

Example/PNDecryptionService/NotificationService.swift
=> [Notify] Optional icon url

Example/IntegrationTests/Push/NotifyTests.swift, Example/IntegrationTests/Stubs/PushMessage.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyMessageRecord.swift, Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyMessage/NotifyMessageSubscriber.swift, Sources/WalletConnectNotify/Types/DataStructures/NotifyMessage.swift
Id param added into message object. Migration not needed
=> [Notify] Message id

Example/DApp/SceneDelegate.swift, Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Example/WalletApp/ApplicationLayer/ProfilingService.swift, Sources/WalletConnectPairing/PairingClient.swift, Sources/WalletConnectPairing/PairingClientProtocol.swift, Sources/WalletConnectPairing/Services/Wallet/WalletPairService.swift, Sources/WalletConnectSign/Engine/Common/ApproveEngine.swift, Sources/WalletConnectSign/Sign/SignClient.swift, Sources/WalletConnectSign/Sign/SignClientFactory.swift, Sources/WalletConnectSign/Sign/SignClientProtocol.swift, Sources/Web3Wallet/Web3WalletClient.swift
=> add mixpanel to w3w

Sources/WalletConnectPairing/PairingClientFactory.swift, Tests/WalletConnectPairingTests/WalletPairServiceTests.swift, Tests/Web3WalletTests/Mocks/PairingClientMock.swift, Tests/Web3WalletTests/Mocks/SignClientMock.swift
=> Mixpanel in w3w fix

Sources/WalletConnectNotify/Client/Wallet/NotifyClientFactory.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyDatabase.swift, Sources/WalletConnectNotify/Types/DataStructures/NotifySubscription.swift
=> [Notify] Subscriptions index by app

Example/IntegrationTests/Push/NotifyTests.swift, Sources/Database/SQLiteQuery.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyDatabase.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyStorage.swift
- db replace method implemented
- empty scope update tests
Context: https://walletconnect.slack.com/archives/C044SKFKELR/p1702421327674859
=> [Notify] Handle empty subscriptions response

Sources/WalletConnectNetworking/NetworkingInteractor.swift, Sources/WalletConnectUtils/RPCHistory/RPCHistory.swift, Sources/WalletConnectUtils/TimeProvider.swift, Tests/WalletConnectUtilsTests/RPCHistoryTests.swift
=> [RPCHistory] Delete on resolve

Example/IntegrationTests/Auth/AuthTests.swift, Example/IntegrationTests/Chat/ChatTests.swift, Example/IntegrationTests/Pairing/PairingTests.swift, Example/IntegrationTests/Push/NotifyTests.swift, Example/IntegrationTests/Sign/SignClientTests.swift, Example/IntegrationTests/Sync/SyncTests.swift, Example/IntegrationTests/XPlatform/Web3Wallet/XPlatformW3WTests.swift, Example/RelayIntegrationTests/RelayClientEndToEndTests.swift, Sources/WalletConnectNetworking/NetworkingInteractor.swift, Sources/WalletConnectRelay/Dispatching.swift, Sources/WalletConnectRelay/Misc/NetworkError.swift, Sources/WalletConnectRelay/NetworkMonitoring.swift, Sources/WalletConnectRelay/RelayClient.swift, Sources/WalletConnectRelay/RelayClientFactory.swift, Tests/RelayerTests/DispatcherTests.swift, Tests/RelayerTests/Helpers/Error+Extension.swift, Tests/RelayerTests/Mocks/DispatcherMock.swift, Tests/RelayerTests/Mocks/NetworkMonitoringMock.swift
=> [Core] Network monitor in dispatcher

.github/workflows/release.yml
Removed the cron job that releases wallet and showcase sample every Monday
* This will allow for only releasing samples once 
=> Remove sample release cron job

Example/IntegrationTests/Push/NotifyTests.swift, Example/WalletApp/PresentationLayer/Wallet/PushMessages/SubscriptionInteractor.swift, Example/WalletApp/PresentationLayer/Wallet/PushMessages/SubscriptionPresenter.swift, Example/WalletApp/PresentationLayer/Wallet/PushMessages/SubscriptionView.swift, Sources/WalletConnectNotify/Client/Wallet/HistoryService.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyClient.swift
=> [Notify] Messages pagination

Example/WalletApp/PresentationLayer/Wallet/PushMessages/SubscriptionPresenter.swift, Example/WalletApp/PresentationLayer/Wallet/PushMessages/SubscriptionView.swift, Sources/Database/SQLiteQuery.swift
=> [Sample] Regression fixes

.env.DApp, .github/workflows/release.yml, Makefile
Can be tested with this CLI command 
`gh workflow run release --ref feat/release_app_option -f app=DApp`
=> Add option to specify what app to release

Example/IntegrationTests/Push/NotifyTests.swift, Example/IntegrationTests/Sign/SignClientTests.swift, Example/Shared/Signer/SOLSigner.swift, Example/WalletApp/PresentationLayer/Wallet/SessionProposal/SessionProposalInteractor.swift, Sources/WalletConnectSign/Engine/Common/SessionEngine.swift, Sources/WalletConnectSign/Namespace.swift, Sources/WalletConnectSign/RejectionReason.swift, Sources/WalletConnectSign/Sign/SessionRequestsProvider.swift, Tests/WalletConnectSignTests/AutoNamespacesValidationTests.swift
fixes a bug with required chains validation
=> Autonamespace fix

.github/workflows/build_artifacts.yml, .github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/cocoapods.yml, .github/workflows/deploy_pages.yml, .github/workflows/release.yml
* Changed M1 runner to move away from Scaleway
* Validated solution works on rs-relay pipeline
=> replaced all instances of M1 runners with Github M1 runners

Example/IntegrationTests/Sign/SignClientTests.swift, Sources/WalletConnectNotify/Client/Wallet/NotifyClient.swift, Sources/WalletConnectSign/Engine/Common/ApproveEngine.swift, Sources/WalletConnectSign/Engine/Common/AuthRequestSubscribersTracking.swift, Sources/WalletConnectSign/Sign/SignClient.swift, Sources/WalletConnectSign/Sign/SignClientFactory.swift, Sources/WalletConnectSign/Sign/SignClientProtocol.swift, Sources/Web3Wallet/Web3WalletClient.swift, Tests/WalletConnectSignTests/AppProposalServiceTests.swift, Tests/WalletConnectSignTests/ApproveEngineTests.swift
=> Auth request publisher not integrated fallback

Example/DApp/SceneDelegate.swift, Example/ExampleApp.xcodeproj/project.pbxproj, Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Example/IntegrationTests/Stubs/Stubs.swift, Example/WalletApp/PresentationLayer/Wallet/SessionProposal/SessionProposalInteractor.swift, Example/WalletApp/PresentationLayer/Wallet/SessionProposal/SessionProposalView.swift, Sources/Auth/AuthClient.swift, Sources/Auth/Services/App/AppRespondSubscriber.swift, Sources/Auth/Services/Wallet/WalletErrorResponder.swift, Sources/Auth/Services/Wallet/WalletRespondService.swift, Sources/Auth/Types/Errors/AuthError.swift, Sources/WalletConnectModal/WalletConnectModal.swift, Sources/WalletConnectSign/Auth/Services/ProposalNamespaceBuilder.swift, Sources/WalletConnectSign/Auth/Services/SessionNamespaceBuilder.swift, Sources/WalletConnectSign/Auth/Services/SignRecap.swift, Sources/WalletConnectSign/Namespace.swift, Tests/WalletConnectSignTests/AutoNamespacesValidationTests.swift, Tests/WalletConnectSignTests/SessionNamespaceBuilderTests.swift
=> Chains as an array

Example/IntegrationTests/Sign/SignClientTests.swift, Sources/WalletConnectSign/Auth/Services/SessionNamespaceBuilder.swift, Tests/WalletConnectSignTests/SessionNamespaceBuilderTests.swift
=> Caip222 include multi chain accounts in a session

Sources/WalletConnectUtils/Cacao/Cacao.swift
Thank you for considering this change, and please let me know if there's any additional context I can provide. I have not tested this using SPM, and wonder if there may be some conflicts with that installation method. Perhaps we can wrap this in some additional flags to make it only available for SPM, if that's the case?
It's worth noting this issue is blocking installation of the more recent versions of this library via cocoapods. 
The following compilation error occurs when installed via cocoapods with DEBUG enabled.
```
37 |         )
38 |         let signature = CacaoSignature(
> 39 |             t: WalletConnectUtils.CacaoSignatureType.eip191,
|                ^ cannot find 'WalletConnectUtils' in scope
40 |             s: "invalid_signature",
41 |             m: nil
42 |         ) …
```
=> Fix import issue with WalletConnectUtils

Example/WalletApp/PresentationLayer/Wallet/AuthRequest/AuthRequestPresenter.swift, Sources/WalletConnectSign/Auth/Services/App/AuthenticatedSessionRecapUrnFactory.swift, Sources/WalletConnectSign/Auth/Services/SignRecapBuilder.swift, Sources/WalletConnectUtils/SIWE/RecapUrnMergingService.swift, Tests/WalletConnectSignTests/SignRecapBuilderTests.swift, Tests/WalletConnectUtilsTests/RecapUrnMergingServiceTests.swift
=> Recap encoding

Example/DApp/SceneDelegate.swift, Example/RelayIntegrationTests/RelayClientEndToEndTests.swift, Sources/WalletConnectRelay/Dispatching.swift, Sources/WalletConnectRelay/RelayClient.swift, Sources/WalletConnectRelay/RelayClientFactory.swift, Sources/WalletConnectRelay/RelayURLFactory.swift, Sources/WalletConnectRelay/SocketConnectionHandler/AutomaticSocketConnectionHandler.swift, Sources/WalletConnectRelay/SocketConnectionHandler/ManualSocketConnectionHandler.swift, Sources/WalletConnectRelay/SocketConnectionHandler/SocketConnectionHandler.swift, Sources/WalletConnectRelay/SocketUrlFallbackHandler.swift, Tests/RelayerTests/AutomaticSocketConnectionHandlerTests.swift, Tests/RelayerTests/DispatcherTests.swift, Tests/RelayerTests/ManualSocketConnectionHandlerTests.swift, Tests/RelayerTests/RelayClientTests.swift
=> Networking improvements

Example/Shared/Signer/ETHSigner.swift, Example/WalletApp/PresentationLayer/Wallet/SessionRequest/SessionRequestPresenter.swift
=> Wallet fix hex encoded request display and signing

Sources/WalletConnectNotify/Client/Wallet/NotifyClient.swift, Sources/WalletConnectPush/PushClient.swift, Sources/WalletConnectPush/PushClientFactory.swift, Sources/WalletConnectPush/UnregisterService.swift, Sources/WalletConnectSign/RejectionReason.swift
=> unregister push on logout

Sources/WalletConnectSign/Engine/Common/SessionEngine.swift, Sources/WalletConnectSign/Services/HistoryService.swift, Sources/WalletConnectSign/Sign/SessionRequestsProvider.swift, Sources/WalletConnectUtils/RPCHistory/RPCHistory.swift, Tests/WalletConnectSignTests/SessionEngineTests.swift
This is a follow up to https://github.com/WalletConnect/WalletConnectSwiftV2/pull/1353.
In addition to clearing stale requests on initialisation, this PR also makes sure requests related to the session are also cleared when the session expires.
Resolves #1343
> [!NOTE]
> This has not yet been tested against the bug as I am still unable to reproduce, this will be tested before merging.
=> Remove pending requests on session expiration

Sources/WalletConnectSign/Auth/Link/LinkAuthRequestSubscriber.swift, Sources/WalletConnectSign/Auth/Link/LinkAuthRequester.swift, Sources/WalletConnectSign/Auth/Services/App/AuthResponseSubscriber.swift, Sources/WalletConnectSign/Auth/Services/App/AuthenticateTransportTypeSwitcher.swift, Sources/WalletConnectSign/Auth/Services/App/SessionAuthRequestService.swift, Sources/WalletConnectSign/Auth/Services/Wallet/AuthRequestSubscriber.swift, Sources/WalletConnectSign/Auth/Services/Wallet/SessionAuthenticateResponder.swift, Sources/WalletConnectSign/Auth/SessionAuthenticatedProtocolMethod.swift, Sources/WalletConnectSign/Engine/Common/ApproveEngine.swift, Sources/WalletConnectSign/LinkAndRelayDispatchers/WalletErrorResponder.swift, Sources/WalletConnectSign/Services/App/AppProposeService.swift, Sources/WalletConnectSign/Types/ProtocolMethods/SessionProposeProtocolMethod.swift
This PR adds specific rejection tags for `sessionPropose` and `sessionAuthenticate` to disambiguate user rejection from genuine failures. 
This will be manually tested.
=> chore(rejection tags): Session rejection tags

Example/DApp/Modules/Sign/SessionAccount/SessionAccountPresenter.swift, Example/DApp/Modules/Sign/SignPresenter.swift, Example/DApp/SceneDelegate.swift, Example/ExampleApp.xcodeproj/project.pbxproj, Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Sources/WalletConnectPairing/Types/AppMetadata.swift, Sources/WalletConnectSign/Auth/Services/App/AuthResponseSubscriber.swift, Sources/WalletConnectSign/LinkAndRelayDispatchers/WalletErrorResponder.swift
=> Link mode w3m

Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Sources/WalletConnectPairing/PairingClient.swift, Sources/WalletConnectPairing/PairingClientProtocol.swift, Sources/WalletConnectPairing/Services/Common/Delete/PairingDeleteRequester.swift, Sources/WalletConnectSign/Services/SignCleanupService.swift, Sources/Web3Wallet/Web3WalletClient.swift
=> optimistic pairing removal

Example/DApp/SceneDelegate.swift
Added Flutter Sample Wallet to Web3Modal
=> Added Flutter sample wallets

Example/DApp/Modules/Sign/SignPresenter.swift, Example/ExampleApp.xcodeproj/project.pbxproj, Example/WalletApp/PresentationLayer/Wallet/ConnectionDetails/ConnectionDetailsInteractor.swift, Example/WalletApp/PresentationLayer/Wallet/ConnectionDetails/ConnectionDetailsModule.swift, Example/WalletApp/PresentationLayer/Wallet/ConnectionDetails/ConnectionDetailsPresenter.swift, Example/WalletApp/PresentationLayer/Wallet/ConnectionDetails/ConnectionDetailsView.swift
=> [Wallet] add chain changed

Example/DApp/SceneDelegate.swift
Added internal flutter wallet reference so iPhone users can test Link Mode.
=> Added Flutter Internal wallet so testers can test Link Mode
