WalletConnect/WalletConnectSwiftV2

- Example/ExampleApp.xcodeproj/project.pbxproj
- Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Example/ExampleApp/Proposer/ProposerViewController.swift
- Example/ExampleApp/Responder/Request/RequestViewController.swift
- Example/ExampleApp/Responder/ResponderViewController.swift
- Example/ExampleApp/Responder/UIAlertController.swift
- Example/ExampleApp/SceneDelegate.swift
- Sources/Relayer/SocketConnectionObserving.swift
- Sources/WalletConnect/Storage/SequenceStore.swift
> #24 filter client sequences

- Example/ExampleApp/Proposer/ProposerViewController.swift
- Sources/Relayer/WakuNetworkRelay.swift
- Sources/WalletConnect/Engine/PairingEngine.swift
- Sources/WalletConnect/Engine/SessionEngine.swift
- Sources/WalletConnect/Relay/WalletConnectRelay.swift
- Sources/WalletConnect/WalletConnectClient.swift
> register background task

- Example/DApp/Connect/ConnectViewController.swift
- Example/ExampleApp.xcodeproj/xcshareddata/xcschemes/Wallet.xcscheme
- Example/ExampleApp/AppDelegate.swift
- Example/ExampleApp/SceneDelegate.swift
> #28 universal linking

- .github/workflows/swift.yml
- Sources/WalletConnect/Engine/PairingEngine.swift
- Sources/WalletConnect/Types/WCMethod.swift
- Sources/WalletConnect/Types/WCRequest.swift
- Sources/WalletConnect/WalletConnectClient.swift
- Sources/WalletConnect/WalletConnectClientDelegate.swift
- Tests/IntegrationTests/ClientDelegate.swift
removes pairing update and upgrade methods,
turns off automatic builds for PRs and push to develop branch
> remove pairing update and upgrade methods

- .github/workflows/swift.yml
- Sources/WalletConnect/Engine/PairingEngine.swift
- Sources/WalletConnect/Types/WCMethod.swift
- Sources/WalletConnect/Types/WCRequest.swift
- Sources/WalletConnect/Types/WalletConnectURI.swift
- Sources/WalletConnect/WalletConnectClient.swift
- Sources/WalletConnect/WalletConnectClientDelegate.swift
- Sources/WalletConnectKMS/Codec/AES_256_CBC_HMAC_SHA256_Codec.swift
- Sources/WalletConnectKMS/Codec/AES_CBC/CBC.swift
- Sources/WalletConnectKMS/Codec/AES_CBC/CBCError.swift
- Sources/WalletConnectKMS/Codec/AES_CBC/Cipher.swift
- Sources/WalletConnectKMS/Codec/HMACAuthenticator.swift
- Sources/WalletConnectKMS/Crypto/CryptoKitWrapper.swift
- Sources/WalletConnectKMS/Crypto/KeyManagementService.swift
- Tests/IntegrationTests/ClientDelegate.swift
- Tests/WalletConnectKMSTests/KeyManagementServiceTests.swift
> #83 add sym key

- Sources/WalletConnect/Engine/PairingEngine.swift
- Sources/WalletConnect/WalletConnectClient.swift
- Sources/WalletConnect/WalletConnectError.swift
> fix compilation failure

- Sources/WalletConnect/Engine/PairingEngine.swift
- Sources/WalletConnect/Engine/SessionEngine.swift
- Sources/WalletConnect/Session.swift
- Sources/WalletConnect/Types/Session/SessionPermissions.swift
- Sources/WalletConnect/Types/Session/SessionProposal.swift
- Sources/WalletConnect/Types/Session/SessionSequence.swift
- Sources/WalletConnect/WalletConnectClient.swift
- Tests/IntegrationTests/ClientTest.swift
- Tests/WalletConnectTests/SessionEngineTests.swift
- Tests/WalletConnectTests/Stub/Session+Stub.swift
- Tests/WalletConnectTests/Stub/Stubs.swift
- Tests/WalletConnectTests/WCRelayTests.swift
- refactor session proposal model
- extract blockchains from permissions is session object
- remove ttl and default to session for 7 days
> refactor session proposal model

- Sources/WalletConnect/Engine/PairingEngine.swift
- Sources/WalletConnect/Engine/SessionEngine.swift
- Sources/WalletConnect/Storage/PairingStorage.swift
- Sources/WalletConnect/Storage/SequenceStore.swift
- Sources/WalletConnect/Storage/SessionStorage.swift
- Tests/WalletConnectTests/Mocks/PairingSequenceStorageMock.swift
- Tests/WalletConnectTests/Mocks/SessionSequenceStorageMock.swift
- Tests/WalletConnectTests/SequenceStoreTests.swift
closes #109 
Simple solution to avoid knowing public keys on expirable sequences.
> Decoupled public key from expirable

- Sources/Relayer/Relayer.swift
> Fixes Bad access when trying to modify subscriptions #156

- .github/workflows/swift.yml
- Sources/WalletConnect/Engine/PairingEngine.swift
- Sources/WalletConnect/Engine/SessionEngine.swift
- Sources/WalletConnect/Engine/SessionStateMachines/ControllerSessionStateMachine.swift
- Sources/WalletConnect/Engine/SessionStateMachines/NonControllerSessionStateMachine.swift
- Sources/WalletConnect/Engine/SessionStateMachines/SessionStateMachineValidating.swift
- Sources/WalletConnect/Relay/WalletConnectRelay.swift
- Sources/WalletConnect/Request.swift
- Sources/WalletConnect/Session.swift
- Sources/WalletConnect/Types/ReasonCode.swift
- Sources/WalletConnect/Types/Session/SessionProposal.swift
- Sources/WalletConnect/Types/Session/SessionType.swift
- Sources/WalletConnect/Types/Session/WCSession.swift
- Sources/WalletConnect/Types/WCMethod.swift
- Sources/WalletConnect/Types/WCRequest.swift
- Sources/WalletConnect/WalletConnectClient.swift
- Sources/WalletConnect/WalletConnectClientDelegate.swift
- Sources/WalletConnect/WalletConnectError.swift
- Tests/IntegrationTests/ClientDelegate.swift
- Tests/IntegrationTests/ClientTest.swift
- Tests/WalletConnectTests/ControllerSessionStateMachineTests.swift
- Tests/WalletConnectTests/NonControllerSessionStateMachineTests.swift
- Tests/WalletConnectTests/PairingEngineTests.swift
- Tests/WalletConnectTests/SessionEngineTests.swift
- Tests/WalletConnectTests/Stub/Session+Stub.swift
- Tests/WalletConnectTests/Stub/Stubs.swift
- Tests/WalletConnectTests/WCRelayTests.swift
> #174 conform to caip 25

- Sources/WalletConnect/Engine/SessionEngine.swift
- Sources/WalletConnect/Types/Session/WCSession.swift
- Tests/IntegrationTests/ClientTest.swift
- Tests/WalletConnectTests/Mocks/MockedRelay.swift
- Tests/WalletConnectTests/SessionEngineTests.swift
- Tests/WalletConnectTests/Stub/Stubs.swift
Unit tests for request authorization check based on namespaces.
> #178 Namespace request tests

- .github/workflows/swift.yml
- Example/DApp/ Accounts/AccountsViewController.swift
- Example/DApp/AccountRequest/AccountRequestViewController.swift
- Example/DApp/ClientDelegate.swift
- Example/DApp/Connect/ConnectViewController.swift
- Example/DApp/SelectChain/SelectChainViewController.swift
- Example/ExampleApp/SessionDetails/SessionDetailsViewController.swift
- Example/ExampleApp/Wallet/WalletViewController.swift
- Sources/WalletConnect/Engine/SessionStateMachines/ControllerSessionStateMachine.swift
- Sources/WalletConnect/Namespace.swift
> #179 Fix example app builds

- Example/ExampleApp/Wallet/WalletViewController.swift
- Sources/WalletConnect/Engine/PairingEngine.swift
- Sources/WalletConnect/Session.swift
- Sources/WalletConnect/Types/Session/SessionProposal.swift
- Sources/WalletConnect/WalletConnectClient.swift
- Sources/WalletConnect/WalletConnectClientDelegate.swift
- Tests/IntegrationTests/ClientTest.swift
- Tests/WalletConnectTests/PairingEngineTests.swift
- adds proposal id as client's `approve()` method parameter.
- removes unused client delegate method
> Client interface

- Example/ExampleApp/SessionProposal/Proposal.swift
- Example/ExampleApp/Wallet/WalletViewController.swift
- Sources/Relayer/NetworkMonitoring.swift
quick fix to not operate on mocked data and allow manual testing
> fix wallet to not operate on mocked data

- Example/DApp/AccountRequest/AccountRequestViewController.swift
use session account for personal_sign request in order to allow testing with js dapp
> Hot fix dapp personal sign

- Sources/WalletConnectSign/Session.swift
- Tests/IntegrationTests/SignClientTests.swift
Re-enable session rejection integration test.
> [Test] #250: Re-enable session reject integration test case

- .github/workflows/swift.yml
- Tests/ChatTests/EndToEndTests.swift
- Tests/IntegrationTests/SignClientTests.swift
- Tests/RelayerTests/RelayClientEndToEndTests.swift
> [CI] SPM Cache

- Sources/WalletConnectKMS/Keychain/KeychainService.swift
- Sources/WalletConnectKMS/Keychain/KeychainStorage.swift
- Sources/WalletConnectRelay/ClientAuth/ClientIdStorage.swift
- Sources/WalletConnectRelay/ClientAuth/SocketAuthenticator.swift
- Tests/RelayerTests/AuthTests/ClientIdStorageTests.swift
- Tests/TestingUtils/Mocks/KeychainStorageMock.swift
> [Core] Feature/#289 ClientID Storage

- Example/ExampleApp/SessionDetails/SessionDetailView.swift
- Example/ExampleApp/SessionDetails/SessionDetailViewModel.swift
**What changed?**
Add account Button to test namespaces updates
> Add test account button

- Example/IntegrationTests/Chat/ChatTests.swift
- Example/Showcase/Classes/DomainLayer/Chat/ChatService.swift
- Sources/Chat/ChatClient.swift
- Sources/Chat/Database.swift
- Sources/Chat/StorageDomainIdentifiers.swift
- Sources/Chat/Types/Message.swift
> [Chat] #325 Messages and threads persistent store

- Example/DApp/ Accounts/AccountsViewController.swift
- Example/IntegrationTests/Chat/ChatTests.swift
- Example/Showcase/Classes/DomainLayer/Chat/ChatService.swift
- Sources/Chat/ChatClient.swift
- Sources/Chat/Database.swift
- Sources/Chat/NetworkingInteractor.swift
- Sources/Chat/ProtocolServices/Common/File.swift
- Sources/Chat/ProtocolServices/Common/LeaveService.swift
- Sources/Chat/ProtocolServices/Invitee/InvitationHandlingService.swift
- Sources/Chat/StorageDomainIdentifiers.swift
- Sources/Chat/Types/Message.swift
> [Chat] #326 resubscribe for threads

- Sources/WalletConnectSign/Engine/Controller/ControllerSessionStateMachine.swift
fix bug in session update namespaces
> update session namespace on response only

- README.md
Adds badges to add higher transparency into whether the CI pipelines are healthy.
See https://github.com/WalletConnect/WalletConnectSwiftV2/tree/derek/feat/badges
> feat: adds workflow badges

- Example/IntegrationTests/Chat/ChatTests.swift
- Example/IntegrationTests/Sign/SignClientTests.swift
- Example/Showcase/Classes/DomainLayer/Chat/ChatFactory.swift
- Sources/Chat/ChatClient.swift
- Sources/Chat/ChatClientFactory.swift
- Sources/WalletConnectSign/Sign/Sign.swift
- Sources/WalletConnectSign/Sign/SignClient.swift
- Sources/WalletConnectSign/Sign/SignClientFactory.swift
**What changed**
ChatClientFactory adn SignClientFactory implemented. Client's init methods clean now
> [Refactor] SDK's Factories 

- .github/workflows/ci.yml
- Example/IntegrationTests/Chat/ChatTests.swift
- Example/IntegrationTests/Relay/RelayClientEndToEndTests.swift
- Example/Showcase/Classes/PresentationLayer/Import/ImportInteractor.swift
- Sources/WalletConnectSign/Types/Session/WCSession.swift
- Tests/RelayerTests/DispatcherTests.swift
**What Changed**
- macos version 12
- xcode version 13.4.1
- Chat integration tests uncommented
> [CI] Upgrade XCode on GH Runner

- .swiftpm/xcode/xcshareddata/xcschemes/AuthTests.xcscheme
- Example/IntegrationTests/Relay/RelayClientEndToEndTests.swift
- Example/Showcase/Classes/PresentationLayer/Import/ImportInteractor.swift
- Package.swift
- Sources/Auth/AuthClient.swift
- Sources/Auth/File.swift
- Sources/Auth/Services/App/AuthRequestService.swift
- Sources/Auth/Services/App/CreatePairingService.swift
- Sources/Auth/Services/Wallet/AuthService.swift
- Sources/Auth/Services/Wallet/PairService.swift
- Sources/Auth/Types/RelayProtocolOptions.swift
- Sources/Auth/Types/RequestParams.swift
- Sources/Auth/Types/RespondParams.swift
- Sources/Auth/Types/WalletConnectURI.swift
- Sources/WalletConnectSign/Types/Common/RelayProtocolOptions.swift
- Sources/WalletConnectSign/Types/RelayProtocolOptions.swift
- Sources/WalletConnectSign/Types/Session/WCSession.swift
- Sources/WalletConnectSign/Types/WalletConnectURI.swift
- Sources/WalletConnectUtils/RelayProtocolOptions.swift
- Sources/WalletConnectUtils/WalletConnectURI.swift
- Tests/AuthTests/AuthClientTest.swift
- Tests/AuthTests/File.swift
- Tests/RelayerTests/DispatcherTests.swift
- Add Auth and AuthTests targets
- Add AuthTests scheme 
- Move WalletConnectURI to Utils target for reusability between Auth and Sign
- Add empty AuthClient and core auth services
> [Auth] #367 auth target

- Sources/WalletConnectKMS/Keychain/KeychainStorage.swift
**What changed**
- KeychainStorage: update key if value exists
> [Core] Allow to override key in keychain

- Sources/WalletConnectRelay/EnvironmentInfo.swift
- Add user agent for mac os
- Enable to build sdk on mac os
> Add user agent for mac os

- .github/workflows/ci.yml
> feat: only run ui test on release

- Sources/Auth/Services/Common/SIWEMessageFormatter.swift
- Sources/Auth/Services/Wallet/AuthRequestSubscriber.swift
- Sources/Auth/Types/AuthPayload.swift
- Sources/Auth/Types/RequestParams.swift
- Tests/AuthTests/AuthRequstSubscriberTests.swift
- Tests/AuthTests/Mocks/SIWEMessageFormatterMock.swift
- Tests/AuthTests/SIWEMessageFormatterTests.swift
- Tests/AuthTests/Stubs/AuthPayload.swift
- Tests/AuthTests/Stubs/RequestParams.swift
- Tests/AuthTests/Stubs/RequestSubscriptionPayload.swift
> [Auth] #394 SIWE messge formatter

- Example/DApp/Sign/Connect/ConnectViewController.swift
- Example/IntegrationTests/Sign/SignClientTests.swift
- Sources/Auth/Auth.swift
- Sources/Auth/AuthClient.swift
- Sources/Auth/Types/Cacao/Cacao.swift
- Sources/Auth/Types/Errors/AuthError.swift
- Sources/Auth/Types/RequestParams.swift
- Sources/WalletConnectRelay/Relay.swift
- Sources/WalletConnectRelay/RelayClient.swift
- Sources/WalletConnectSign/Engine/Common/PairingEngine.swift
- Sources/WalletConnectSign/Sign/Sign.swift
- Sources/WalletConnectSign/Sign/SignClient.swift
Updates public api docs for Auth, Sign and Relay
requires next release tag to be `0.11.0`
Resolves #464 
does not require testing
> [API] Update public api docs

- Sources/Chat/NetworkingInteractor.swift
- Sources/WalletConnectKMS/Serialiser/Serializer.swift
- Sources/WalletConnectKMS/Serialiser/Serializing.swift
- Sources/WalletConnectRelay/Dispatching.swift
- Sources/WalletConnectSign/Engine/Common/SessionEngine.swift
- Sources/WalletConnectSign/Engine/Controller/ControllerSessionStateMachine.swift
- Tests/WalletConnectSignTests/Mocks/SerializerMock.swift
- Unexpected keyNotFound error removed
- Serializer refactor
- Logging improvements
Resolves #420
Perform steps from #420 manually
> [Logger] Unexpected keyNotFound error #420

- Example/ExampleApp.xcodeproj/project.pbxproj
- Example/Showcase/Other/Info.plist
Add info plist values to showcase app
> Add info plist values to showcase app

- .github/actions/ci/action.yml
> feat: allow to pass relay endpoint

- Sources/WalletConnectRelay/EnvironmentInfo.swift
> update user agent

- Example/DApp/SceneDelegate.swift
- Example/ExampleApp/SceneDelegate.swift
- Example/IntegrationTests/Auth/AuthTests.swift
- Example/IntegrationTests/Chat/ChatTests.swift
- Example/IntegrationTests/Relay/RelayClientEndToEndTests.swift
- Example/IntegrationTests/Sign/SignClientTests.swift
we have some weird metrics for old project id so we need to localize the problem.
> Change project id

- Example/ExampleApp.xcodeproj/project.pbxproj
- Example/IntegrationTests/Sign/Helpers/ClientDelegate.swift
- Example/IntegrationTests/Sign/Helpers/XCTest.swift
- Example/IntegrationTests/Sign/SignClientTests.swift
- Example/IntegrationTests/Stubs/Stubs.swift
- Sources/WalletConnectSign/Engine/Controller/ControllerSessionStateMachine.swift
- Sources/WalletConnectSign/Types/Session/WCSession.swift
- Tests/WalletConnectSignTests/ControllerSessionStateMachineTests.swift
- Tests/WalletConnectSignTests/Helpers/Error+Extension.swift
Restore Sign integration tests
Resolves #250
> #250 sign restore integration tests

- Example/ExampleApp/SceneDelegate.swift
- Example/ExampleApp/SessionProposal/Proposal.swift
> wallet hot fix

- Example/ExampleApp.xcodeproj/project.pbxproj
- Example/IntegrationTests/Auth/AuthTests.swift
- Example/IntegrationTests/Chat/ChatTests.swift
- Example/IntegrationTests/Pairing/PairingTests.swift
- Example/IntegrationTests/Relay/RelayClientEndToEndTests.swift
- Example/IntegrationTests/Sign/SignClientTests.swift
- Example/IntegrationTests/Stubs/InputConfig.swift
> [CI] Default timeout increased

- Example/IntegrationTests/Auth/AuthTests.swift
- Example/IntegrationTests/Chat/ChatTests.swift
- Example/IntegrationTests/Relay/RelayClientEndToEndTests.swift
- Example/IntegrationTests/Sign/SignClientTests.swift
Hotfix - increase timeouts in integration tests
> hotfix - increase timeouts

- Example/ExampleApp.xcodeproj/project.pbxproj
- Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Package.swift
- Web3 moved to WalletConnect repo
- Version 1.0.0 released and imported
> [Core] Web3 from WalletConnect repo #426

- Example/DApp/Auth/AuthViewModel.swift
- Example/DApp/Sign/SignCoordinator.swift
- Example/IntegrationTests/Auth/AuthTests.swift
- Example/Showcase/Classes/ApplicationLayer/Configurator/ThirdPartyConfigurator.swift
- Example/Showcase/Classes/ApplicationLayer/SceneDelegate.swift
- Example/Showcase/Classes/PresentationLayer/Wallet/Wallet/WalletInteractor.swift
- Sources/Auth/Auth.swift
- Sources/Auth/AuthClient.swift
- Sources/Auth/AuthClientFactory.swift
- Sources/WalletConnectPairing/PairingClient.swift
- Sources/WalletConnectPairing/PairingRegisterer.swift
- Sources/WalletConnectPairing/Services/Common/PairingsProvider.swift
- Sources/WalletConnectSign/Sign/Sign.swift
- Tests/AuthTests/Mocks/PairingRegistererMock.swift
> #526 remove pairing methods from auth

- .gitignore
- Configuration.xcconfig
- default host value in Configuration file
> [Env] Default relay host

- Sources/WalletConnectRelay/EnvironmentInfo.swift
- EnvironmentInfo operatingSystem for tvOS
> [Bugfix] tvOS operatingSystem

- Example/IntegrationTests/Pairing/PairingTests.swift
- Sources/WalletConnectPairing/Types/PairError.swift
> [Pair] update method unsupported

- Sources/WalletConnectNetworking/Networking.swift
- Sources/WalletConnectPairing/Services/Common/Ping/PingResponseSubscriber.swift
Pairing request subscription doesn't work in some cases
> [Pair] Pairing request subscription fix

- Sources/WalletConnectPairing/PairingInteracting.swift
add debug availability for cleanup method 
Resolves #551
> [Pairing] add debug availability for cleanup method

- Sources/WalletConnectRelay/EnvironmentInfo.swift
> [Core] v1.0.2 sdk version

- Example/Showcase/Classes/PresentationLayer/Wallet/Scan/Views/ScanQRView.swift
> [Showcase] Stop capture session after scan

- Sources/WalletConnectRelay/EnvironmentInfo.swift
> [Core] User agent v1.0.3

- Example/Showcase/Classes/PresentationLayer/Wallet/Scan/Views/ScanQRView.swift
- Sources/Commons/AnyCodable.swift
- Sources/Commons/AnyCodableError.swift
- Sources/WalletConnectRelay/EnvironmentInfo.swift
- Tests/CommonsTests/AnyCodableTests.swift
Including https://github.com/WalletConnect/WalletConnectSwiftV2/pull/564
> Hotfix v1.0.4

- Sources/WalletConnectRelay/BundleFinder.swift
- Sources/WalletConnectRelay/EnvironmentInfo.swift
- WalletConnectSwiftV2.podspec
> [Infra] Resources Bundle fix

- Sources/WalletConnectNetworking/NetworkingInteractor.swift
> [Sign] remove force unwrap from request

- .github/workflows/set-user-agent.yml
> [CI] GH token for User Agent job

- README.md
> [Readme] Cocoapods instructions

- .swiftpm/xcode/xcshareddata/xcschemes/WalletConnectVerify.xcscheme
- Example/ExampleApp.xcodeproj/project.pbxproj
- Example/ExampleApp/AppDelegate.swift
- Package.swift
- Sources/WalletConnectVerify/AppAttestationRegistrer.swift
- Sources/WalletConnectVerify/AssertionRegistrer.swift
- Sources/WalletConnectVerify/AttestChallengeProvider.swift
- Sources/WalletConnectVerify/AttestKeyGenerator.swift
- Sources/WalletConnectVerify/Constants.swift
- Sources/WalletConnectVerify/KeyAttestationService.swift
- Sources/WalletConnectVerify/OriginVerifier.swift
- Sources/WalletConnectVerify/VerifyClient.swift
- Sources/WalletConnectVerify/VerifyClientFactory.swift
- Sources/WalletConnectVerify/VerifyStorageIdentifier.swift
- Tests/VerifyTests/AppAttestationRegistrerTests.swift
- Tests/VerifyTests/Mocks/AttestChallengeProvidingMock.swift
- Tests/VerifyTests/Mocks/AttestKeyGeneratingMock.swift
- Tests/VerifyTests/Mocks/KeyAttestingMock.swift
- add verify target
- add verify client and App Attestation Registrer implementation
Resolves #588 #582 
- unit tests
> Add Verify target

- Example/IntegrationTests/Auth/AuthTests.swift
- Example/IntegrationTests/Auth/Signer/CacaoSignerTests.swift
- Example/Showcase/Classes/ApplicationLayer/Configurator/ThirdPartyConfigurator.swift
- Example/Showcase/Classes/PresentationLayer/Wallet/AuthRequest/AuthRequestInteractor.swift
- Example/Showcase/Classes/PresentationLayer/Wallet/AuthRequest/AuthRequestPresenter.swift
- Sources/Auth/Auth.swift
- Sources/Auth/AuthClient.swift
- Sources/Auth/AuthClientFactory.swift
- Sources/Auth/AuthConfig.swift
- Sources/Auth/Services/App/AppRespondSubscriber.swift
- Sources/Auth/Services/Common/SIWEMessageFormatter.swift
- Sources/Auth/Services/Signer/MessageSigner.swift
- Sources/Auth/Services/Signer/MessageSignerFactory.swift
- Sources/Auth/Services/Wallet/PendingRequestsProvider.swift
- Sources/Auth/Services/Wallet/WalletRequestSubscriber.swift
- Sources/Auth/Types/AuthPayload.swift
- Sources/Auth/Types/ProtocolRPCParams/AuthRequestParams.swift
- Sources/Auth/Types/Public/AuthRequest.swift
- Tests/AuthTests/AppRespondSubscriberTests.swift
- Tests/AuthTests/Mocks/SIWEMessageFormatterMock.swift
- Tests/AuthTests/SIWEMessageFormatterTests.swift
- Tests/AuthTests/Stubs/MessageSignerMock.swift
- Tests/AuthTests/Stubs/RequestSubscriptionPayload.swift
- Tests/AuthTests/WalletRequestSubscriberTests.swift
Resolves https://github.com/WalletConnect/WalletConnectSwiftV2/issues/595
Specs: https://github.com/WalletConnect/walletconnect-docs/pull/355
> [Auth] Multi account support

- .github/workflows/ci.yml
> [CI] XCode 14.1

- Sources/WalletConnectUtils/Logger.swift
Add timestamp HH:mm:ss.SSSS to debug logs
> Add timestamp to logging

- README.md
> Update README with Web3Wallet migration guide

- WalletConnectSwiftV2.podspec
> [Web3Wallet] CocoaPods 1.2.1

- Sources/WalletConnectSign/Engine/Common/ApproveEngine.swift
- Sources/WalletConnectSign/Services/App/AppProposeService.swift
- Sources/WalletConnectSign/Session.swift
- Sources/WalletConnectSign/Types/Session/SessionProposal.swift
- Tests/WalletConnectSignTests/ApproveEngineTests.swift
- Tests/WalletConnectSignTests/Stub/Stubs.swift
Base on https://walletconnect.slack.com/archives/C03RR5C0F7X/p1673428495333859
> Extend 'Session' with 'pairingTopic'

- Sources/WalletConnectPush/Client/Dapp/ProposalResponseSubscriber.swift
- Sources/WalletConnectPush/Client/Wallet/PushRequestResponder.swift
- Sources/WalletConnectPush/Push.swift
After establishing Push Subscription exchange key pair can be removed.
> [Push] Remove exchange key pair

- Example/DApp/Sign/Accounts/AccountsViewController.swift
- Example/DApp/Sign/SignCoordinator.swift
- Example/ExampleApp.xcodeproj/project.pbxproj
- Example/PushDecryptionService/NotificationService.swift
- Sources/WalletConnectPush/Types/PushSubscription.swift
integrate Push into a sample dapp
manually with swift old example wallet
> [Push] Dapp push example

- Example/DApp/Sign/Connect/ConnectViewController.swift
- Example/DApp/Sign/SelectChain/SelectChainViewController.swift
- Example/ExampleApp/SessionDetails/SessionDetailViewModel.swift
- Example/ExampleApp/Wallet/WalletViewController.swift
- Example/WalletApp/PresentationLayer/Wallet/SessionProposal/SessionProposalInteractor.swift
- Sources/WalletConnectSign/Namespace.swift
- Sources/WalletConnectSign/Types/Session/WCSession.swift
- Tests/WalletConnectSignTests/NamespaceValidationTests.swift
- Tests/WalletConnectSignTests/Stub/Stubs.swift
- Tests/WalletConnectSignTests/WCSessionTests.swift
> Remove namespace extensions

- Sources/WalletConnectEcho/EchoClientFactory.swift
- Sources/WalletConnectEcho/Register/EchoRegisterService.swift
- Sources/WalletConnectEcho/Register/EcoResponse.swift
fix response status echo server
manually with logs
> [Echo] fix echo registry status

- Example/IntegrationTests/Chat/RegistryTests.swift
- Sources/WalletConnectRouter/Router.m
More info: https://github.com/WalletConnect/WalletConnectSwiftV2/pull/696
> [Router] Compatibility with MacOS

- .env.Showcase
- .env.WalletApp
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .gitignore
- Example/ExampleApp.xcodeproj/project.pbxproj
- Makefile
- fastlane/Appfile
- fastlane/Fastfile
> [CI] Scheduled release

- Example/WalletApp/PresentationLayer/Wallet/SessionProposal/SessionProposalInteractor.swift
- Sources/WalletConnectUtils/Extensions/String+CAIPs.swift
To pass chains like `cosmos:kava_2222-10`
> Update regex for chains

- Sources/JSONRPC/RPCID.swift
- Sources/WalletConnectRelay/RPC/WalletConnectRPCID.swift
- Sources/WalletConnectUtils/JsonRecID.swift
- Tests/WalletConnectSignTests/WCResponseTests.swift
Based on https://gist.github.com/pedrouid/eb89f3ac161fe61f5be1fc2d1f6625b6
> Increase RPCID entropy

- Sources/JSONRPC/RPCID.swift
- Sources/WalletConnectRelay/RPC/WalletConnectRPCID.swift
- Sources/WalletConnectUtils/JsonRecID.swift
- Tests/WalletConnectSignTests/WCResponseTests.swift
Reverts WalletConnect/WalletConnectSwiftV2#717
> Revert "Increase RPCID entropy"

- Sources/WalletConnectRelay/AppStateObserving.swift
- Sources/WalletConnectRelay/Dispatching.swift
- Sources/WalletConnectRelay/SocketConnectionHandler/AutomaticSocketConnectionHandler.swift
- Sources/WalletConnectRelay/SocketConnectionHandler/ManualSocketConnectionHandler.swift
- Sources/WalletConnectRelay/SocketConnectionHandler/SocketConnectionHandler.swift
- Tests/RelayerTests/AutomaticSocketConnectionHandlerTests.swift
More context: https://github.com/WalletConnect/WalletConnectSwiftV2/pull/691
> Ensure application state read from main thread

- Sources/Web3Wallet/Web3Wallet.swift
- Sources/Web3Wallet/Web3WalletClient.swift
- Sources/Web3Wallet/Web3WalletClientFactory.swift
- Sources/Web3Wallet/Web3WalletImports.swift
> Web3Wallet cocoapods

- Sources/Web3Wallet/Web3WalletClient.swift
> [Web3Wallet] TargetEnvironment changed to DEBUG

- Sources/Web3Inbox/Web3Inbox.swift
> [W3I] Configure chat

- Example/IntegrationTests/Auth/ENS/ENSResolverTests.swift
> [CI] Changed ENSResolverTests address

- Sources/WalletConnectKMS/Keychain/KeychainStorage.swift
> update to kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly

- Sources/WalletConnectKMS/Keychain/KeychainStorage.swift
> revert to kSecAttrAccessibleWhenUnlockedThisDeviceOnly

- .github/workflows/ci.yml
- Example/ExampleApp.xcodeproj/project.pbxproj
- Example/IntegrationTests/Auth/Signer/EIP55Tests.swift
- Example/IntegrationTests/Auth/Signer/SignerTests.swift
- Example/IntegrationTests/Chat/RegistryTests.swift
- Sources/Chat/Types/Payloads/AcceptPayload.swift
- Sources/Chat/Types/Payloads/InvitePayload.swift
- Sources/Chat/Types/Payloads/MessagePayload.swift
- Sources/Chat/Types/Payloads/ReceiptPayload.swift
- Sources/WalletConnectIdentity/IdentityKeyAPI.swift
- Sources/WalletConnectIdentity/IdentityNetworkService.swift
- Sources/WalletConnectIdentity/IdentityNetworking.swift
- Sources/WalletConnectIdentity/IdentityService.swift
- Sources/WalletConnectIdentity/Types/IDAuthPayload.swift
- Sources/WalletConnectPush/RPCRequests/AcceptSubscriptionJWTPayload.swift
- Sources/WalletConnectSigner/Ethereum/EIP55/EIP55.swift
- Sources/WalletConnectSigner/Ethereum/ENS/ENSResolver.swift
- Sources/WalletConnectUtils/Account.swift
- Tests/ChatTests/Mocks/IdentityNetwotkServiceMock.swift
- unregister api changed
- act field
- do not run ci on push
> [JWT] Unregister + act field

- Sources/WalletConnectUtils/SIWE/SIWEMessage.swift
> [Cacao] Do not lowercase address 

- Example/WalletApp/PresentationLayer/Wallet/PushMessages/Models/PushMessageViewModel.swift
- Example/WalletApp/PresentationLayer/Wallet/PushMessages/PushMessagesInteractor.swift
- Example/WalletApp/PresentationLayer/Wallet/PushMessages/PushMessagesPresenter.swift
- Example/WalletApp/PresentationLayer/Wallet/PushMessages/PushMessagesView.swift
Small improvements
Resolves some of the feedback here
https://github.com/WalletConnect/WalletConnectSwiftV2/issues/772
> [WalletApp] PN Screen - Display and sort by publishedAt, subscribe to PN publisher

- Example/IntegrationTests/Auth/AuthTests.swift
- Example/IntegrationTests/Chat/ChatTests.swift
- Example/IntegrationTests/Pairing/PairingTests.swift
- Example/IntegrationTests/Push/PushTests.swift
- Example/IntegrationTests/Sign/SignClientTests.swift
log client id in integration tests, so we can better analyse the issues in relay pipeline 
> Add client id to integration tests logs

- Sources/Web3Inbox/WebView/WebViewRequestSubscriber.swift
> [W3I] Subscriber name fixed

- .github/actions/build/action.yml
- .github/actions/run_tests_without_building/action.yml
- .github/workflows/build_artifacts.yml
- Fixes some silly mistakes/typos when populating and passing parameters.
- Adds inputs to `build_artifacts` workflow when using `workflow_dispatch` event
> fix: gh action typos and inputs

- Sources/WalletConnectSign/Namespace.swift
When I use AutoNamespaces's build function, I can't catch the error detail.
> [W3W] make Auto Namespaces Error Public

- Example/ExampleApp.xcodeproj/IntegrationTests.xctestplan
- Example/ExampleApp.xcodeproj/project.pbxproj
- Example/IntegrationTests/Push/PushTests.swift
- Example/SmokeTests.xctestplan
- Sources/WalletConnectPush/Client/Wallet/ProtocolEngine/wc_notifyUpdate/NotifyUpdateRequester.swift
- Sources/WalletConnectPush/Client/Wallet/ProtocolEngine/wc_notifyUpdate/NotifyUpdateResponseSubscriber.swift
- Sources/WalletConnectPush/Client/Wallet/ProtocolEngine/wc_pushSubscribe/PushSubscribeRequester.swift
- Sources/WalletConnectPush/Client/Wallet/ProtocolEngine/wc_pushSubscribe/PushSubscribeResponseSubscriber.swift
- Sources/WalletConnectPush/Client/Wallet/WalletPushClient.swift
- Sources/WalletConnectPush/Client/Wallet/WalletPushClientFactory.swift
- Sources/WalletConnectPush/Types/NotificationScope.swift
- Sources/WalletConnectPush/Types/NotificationType.swift
- Sources/WalletConnectPush/Types/PushSubscription.swift
- Sources/WalletConnectUtils/SIWE/SIWEMessage.swift
- Sources/Web3Inbox/PushClientProxy/PushClientProxy.swift
- Tests/AuthTests/SIWEMessageFormatterTests.swift
> Subscribe scope

- Package.swift
Pinning QRCode dependency to use branch in our fork
https://github.com/WalletConnect/WalletConnectSwiftV2/issues/854
> [SPM] Fix QRCode dependency version

- Example/RelayIntegrationTests/RelayClientEndToEndTests.swift
- Sources/WalletConnectRelay/RelayClient.swift
> update relay e2e tests logs

- .github/actions/run_tests_without_building/action.yml
- .github/workflows/ci.yml
move slack notification action to run tests without building
> [CI/CD] slack notification action

- .github/actions/build/action.yml
- .github/workflows/build_artifacts.yml
- .github/workflows/ci.yml
- .gitignore
- Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> [CI] More strict SPM caching

- .github/actions/run_tests_without_building/action.yml
- Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Example/RelayIntegrationTests/RelayClientEndToEndTests.swift
- Example/SmokeTests.xctestplan
> Slack notifications fix

- .github/actions/build/action.yml
- .github/workflows/ci.yml
This needs to be merged in develop/main first to take effect
> [CI/CD] Use correct ref for cache key

- Example/IntegrationTests/Pairing/PairingTests.swift
- Sources/WalletConnectPush/Client/Wallet/ProtocolEngine/wc_notifyPropose/NotifyProposeResponder.swift
- Sources/WalletConnectPush/Client/Wallet/ProtocolEngine/wc_notifyPropose/NotifyProposeSubscriber.swift
- Sources/WalletConnectPush/Client/Wallet/ProtocolEngine/wc_pushMessage/PushMessageSubscriber.swift
- Sources/WalletConnectPush/Client/Wallet/WalletPushClient.swift
- Sources/WalletConnectPush/Client/Wallet/WalletPushClientFactory.swift
- Sources/WalletConnectPush/Types/PushError.swift
wallet sdk responds with an error if subscription already exists for a given domain
manually and with integration tests
> [Push] propose error

- Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Example/IntegrationTests/Push/PushTests.swift
- Sources/WalletConnectPush/Client/Common/DeletePushSubscriptionSubscriber.swift
- Sources/WalletConnectPush/Client/Dapp/DappPushClient.swift
- Sources/WalletConnectPush/Client/Wallet/WalletPushClient.swift
- Sources/WalletConnectPush/Client/Wallet/WalletPushClientFactory.swift
- Sources/Web3Inbox/PushClientProxy/PushClientRequestSubscriber.swift
> [Push/W3I] Handle delete subscription in wallet

- Sources/Web3Inbox/Web3InboxClient.swift
- Sources/Web3Inbox/Web3InboxClientFactory.swift
- Sources/Web3Inbox/WebView/WebViewProxy.swift
- Sources/Web3Inbox/WebView/WebViewRefreshHandler.swift
Fixes loosing cached params in a webview and logging out the user.
Observes changes to the URL of a WKWebView and reloads the initial URL if the new URL contains "/login". 
timer prevents inf loop.
> [W3I] Fix web view refresh

- Example/IntegrationTests/Push/Publisher.swift
Prepares integration tests for [ spec changes ](https://github.com/WalletConnect/walletconnect-docs/pull/841/files)
> [Push] Cast server bearer auth

- Sources/WalletConnectNotify/Client/Common/NotifyDecryptionService.swift
- Sources/WalletConnectNotify/Client/Wallet/NotifySyncService.swift
- Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyMessage/NotifyMessageSubscriber.swift
- Sources/WalletConnectNotify/Types/Payload/NotifyMessagePayload.swift
- NotifyMessage JWT implemented
- NotifyDecryptionService updated
- History response parsing updated
> [Notify] NotifyMessage JWT

- Example/WalletApp/PresentationLayer/Wallet/Web3Inbox/Web3InboxViewController.swift
Subscription's screen url contains topic: 
ex: `https://web3inbox-dev-hidden.vercel.app/notifications/88a71f553de0f47443984a482f9d2d95243b2b2ec2af0f47888b83da84b843f8`
> [W3I] Copy URL button

- .github/workflows/build_artifacts.yml
- .github/workflows/deploy_pages.yml
Successful run https://github.com/WalletConnect/WalletConnectSwiftV2/actions/runs/5818750393
> [CI] Use self-hosted runners for build artifacts

- Example/IntegrationTests/Push/NotifyTests.swift
- Example/WalletApp/ApplicationLayer/ConfigurationService.swift
- Sources/WalletConnectNotify/Client/Common/DeleteNotifySubscriptionService.swift
- Sources/WalletConnectNotify/Client/Common/DeleteNotifySubscriptionSubscriber.swift
- Sources/WalletConnectNotify/Client/Wallet/NotifyClientFactory.swift
- Sources/WalletConnectNotify/Client/Wallet/NotifyStorage.swift
- Sources/WalletConnectNotify/Client/Wallet/NotifySyncService.swift
- Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyMessage/NotifyMessageSubscriber.swift
- Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyUpdate/NotifyUpdateRequester.swift
- Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyUpdate/NotifyUpdateResponseSubscriber.swift
- Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_pushSubscribe/NotifySubscribeRequester.swift
- Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_pushSubscribe/NotifySubscribeResponseSubscriber.swift
- Sources/WalletConnectNotify/Client/Wallet/WebDidResolver.swift
- Sources/WalletConnectNotify/Notify.swift
- Sources/WalletConnectNotify/NotifyConfig.swift
- Sources/WalletConnectNotify/Types/Payload/NotifyDeletePayload.swift
- Sources/WalletConnectNotify/Types/Payload/NotifyDeleteResponsePayload.swift
- Sources/WalletConnectNotify/Types/Payload/NotifyMessagePayload.swift
- Sources/WalletConnectNotify/Types/Payload/NotifyMessageReceiptPayload.swift
- Sources/WalletConnectNotify/Types/Payload/NotifySubscriptionPayload.swift
- Sources/WalletConnectNotify/Types/Payload/NotifySubscriptionResponsePayload.swift
- Sources/WalletConnectNotify/Types/Payload/NotifyUpdatePayload.swift
- Sources/WalletConnectNotify/Types/Payload/NotifyUpdateResponsePayload.swift
- Sources/WalletConnectNotify/Types/WebDidDoc.swift
- Sources/WalletConnectSync/Stores/SyncStore.swift
- Sources/Web3Inbox/Web3Inbox.swift
> [Notify] JWT's protocol changes

- Example/ExampleApp.xcodeproj/xcshareddata/xcschemes/BuildAll.xcscheme
> Add x platform test plan to buildAll

- Example/Shared/DefaultCryptoProvider.swift
- Example/Showcase/Classes/PresentationLayer/Web3Inbox/Web3InboxViewController.swift
- Example/WalletApp/PresentationLayer/Wallet/Notifications/NotificationsInteractor.swift
- Example/WalletApp/PresentationLayer/Wallet/PushMessages/PushMessagesInteractor.swift
- Sources/WalletConnectNotify/Notify.swift
- Sources/Web3Inbox/Web3Inbox.swift
> [Notify] renaming

- Configuration.xcconfig
- Example/IntegrationTests/Auth/AuthTests.swift
- Example/IntegrationTests/Chat/ChatTests.swift
- Example/IntegrationTests/History/HistoryTests.swift
- Example/IntegrationTests/Pairing/PairingTests.swift
- Example/IntegrationTests/Push/NotifyTests.swift
- Example/IntegrationTests/Sign/SignClientTests.swift
- Example/IntegrationTests/Sync/SyncTests.swift
- Example/IntegrationTests/XPlatform/Web3Wallet/XPlatformW3WTests.swift
- Example/RelayIntegrationTests/RelayClientEndToEndTests.swift
- Example/WalletApp/ApplicationLayer/ConfigurationService.swift
- Example/WalletApp/ApplicationLayer/Configurator/ThirdPartyConfigurator.swift
- Example/WalletApp/ApplicationLayer/LoggingService.swift
- Sources/Chat/ChatClientFactory.swift
- Sources/WalletConnectHistory/HistoryClientFactory.swift
- Sources/WalletConnectKMS/Serialiser/Serializer.swift
- Sources/WalletConnectKMS/Serialiser/Serializing.swift
- Sources/WalletConnectNetworking/NetworkingClient.swift
- Sources/WalletConnectNetworking/NetworkingClientFactory.swift
- Sources/WalletConnectNetworking/NetworkingInteractor.swift
- Sources/WalletConnectNotify/Client/Common/NotifyDecryptionService.swift
- Sources/WalletConnectNotify/Client/Wallet/NotifyClientFactory.swift
- Sources/WalletConnectPush/PushClientFactory.swift
- Sources/WalletConnectRelay/RelayClient.swift
- Sources/WalletConnectRelay/RelayClientFactory.swift
- Sources/WalletConnectUtils/Logger/ConsoleLogger.swift
- Sources/Web3Inbox/Web3InboxClientFactory.swift
- Tests/WalletConnectKMSTests/SerialiserTests.swift
- Add KMS logger
- Allows to set logging level at Networking instance
- Add path, function name and class for every log message
> [Core] Add Kms logger

- Example/WalletApp/PresentationLayer/Wallet/Main/MainPresenter.swift
- Example/WalletApp/PresentationLayer/Wallet/Main/Model/TabPage.swift
Reenable native notify integration
> [WalletApp, Notify] Reenable native notify integration

- .github/workflows/release.yml
- Configuration.xcconfig
- Example/ExampleApp.xcodeproj/project.pbxproj
- Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Example/WalletApp/ApplicationLayer/ConfigurationService.swift
- Example/WalletApp/ApplicationLayer/Configurator/ThirdPartyConfigurator.swift
- Example/WalletApp/ApplicationLayer/LoggingService.swift
- Example/WalletApp/ApplicationLayer/ProfilingService.swift
- Example/WalletApp/Common/InputConfig.swift
- Example/WalletApp/Other/Info.plist
- Example/WalletApp/PresentationLayer/Wallet/PushMessages/PushMessagesPresenter.swift
- Makefile
- Sources/WalletConnectNetworking/NetworkingInteractor.swift
- Sources/WalletConnectNotify/Client/Wallet/NotifyClient.swift
- Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyMessage/NotifyMessageSubscriber.swift
- Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_pushSubscribe/NotifySubscribeResponseSubscriber.swift
- Sources/WalletConnectRelay/RelayClient.swift
- Sources/WalletConnectUtils/Logger/ConsoleLogger.swift
- Sources/WalletConnectUtils/Logger/Log.swift
- Sources/Web3Inbox/Web3InboxClient.swift
- Sources/Web3Inbox/Web3InboxClientFactory.swift
- Sources/Web3Inbox/WebView/WebViewProxy.swift
- fastlane/Fastfile
> Add Mixpanel

- Sources/WalletConnectNotify/Client/Common/NotifyResubscribeService.swift
- Sources/WalletConnectNotify/Client/Wallet/NotifyClientFactory.swift
> [Notify] Add more logs

- Example/IntegrationTests/Push/NotifyTests.swift
- Sources/WalletConnectNotify/Client/Wallet/NotifyClient.swift
- Sources/WalletConnectNotify/Client/Wallet/NotifyConfigProvider.swift
- Sources/WalletConnectNotify/Client/Wallet/NotifySubscriptionsBuilder.swift
- Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyWatchSubscriptions/NotifyWatchSubscriptionsRequester.swift
- Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_pushSubscribe/NotifySubscribeRequester.swift
- Sources/WalletConnectNotify/Client/Wallet/WebDidResolver.swift
- Sources/WalletConnectNotify/Types/DataStructures/NotificationConfig.swift
- Sources/WalletConnectNotify/Types/DataStructures/NotifyServerSubscription.swift
> Notify config

- Sources/WalletConnectNotify/Client/Wallet/NotifyWebDidResolver.swift
- Sources/WalletConnectNotify/Types/JWTPayloads/NotifyMessageReceiptPayload.swift
- Sources/Web3Inbox/NotifyClientProxy/NotifyClientProxy.swift
> rename receiptAuth to responseAuth

- Sources/WalletConnectKMS/Crypto/KeyManagementService.swift
- Sources/WalletConnectNotify/Client/Wallet/NotifyConfigProvider.swift
- Sources/WalletConnectNotify/Client/Wallet/NotifySubscriptionsBuilder.swift
- Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyUpdate/NotifyUpdateResponseSubscriber.swift
- Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyWatchSubscriptions/NotifyWatchSubscriptionsRequester.swift
- Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_pushSubscribe/NotifySubscribeRequester.swift
- Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_pushSubscribe/NotifySubscribeResponseSubscriber.swift
> Key y generate once

- Sources/Web3Inbox/NotifyClientProxy/NotifyClientRequest.swift
- Sources/Web3Inbox/NotifyClientProxy/NotifyClientRequestSubscriber.swift
> add notify_subscriptions_changed  to w3i

- Sources/WalletConnectNotify/Client/Wallet/NotifyClientFactory.swift
- Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifySubscriptionsChanged/NotifySubscriptionsChangedRequestSubscriber.swift
> Add group keychain into watch subscriptions

- Sources/WalletConnectNotify/Types/JWTPayloads/NotifyMessagePayload.swift
> remove aud from message

- Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifySubscriptionsChanged/NotifySubscriptionsChangedRequestSubscriber.swift
- Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyWatchSubscriptions/NotifyWatchSubscriptionsResponseSubscriber.swift
- Sources/WalletConnectNotify/Types/JWTPayloads/NotifyMessagePayload.swift
> Save keys on watch and change

- Sources/WalletConnectNotify/Client/Wallet/NotifyClient.swift
- Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyWatchSubscriptions/NotifyWatchSubscriptionsRequester.swift
- Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyWatchSubscriptions/NotifyWatchSubscriptionsResponseSubscriber.swift
> watch subscriptions on socket connection

- Example/WalletApp/ApplicationLayer/ConfigurationService.swift
> register notify

- Example/IntegrationTests/Push/NotifyTests.swift
- Sources/WalletConnectNotify/Client/Wallet/NotifyClient.swift
- Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyUpdate/NotifyUpdateResponseSubscriber.swift
> Tests fixes

- Example/ExampleApp.xcodeproj/xcshareddata/xcschemes/WalletConnect.xcscheme
- Tests/ChatTests/RegistryServiceTests.swift
> disable chat tests

- Sources/WalletConnectUtils/Logger/ConsoleLogger.swift
Recreated https://github.com/WalletConnect/WalletConnectSwiftV2/pull/1117 PR
Fix error when integrated with Cocoapods
Resolves # (issue )
https://github.com/WalletConnect/WalletConnectSwiftV2/issues/1071
Thanks @SunZhiC for contribution 
> [Cocoapods] WalletConnectUtils link removed

- .github/actions/run_tests_without_building/action.yml
- .github/workflows/ci.yml
- Configuration.xcconfig
- Example/ExampleApp.xcodeproj/IntegrationTests.xctestplan
- Example/IntegrationTests/Push/NotifyTests.swift
- Example/IntegrationTests/Push/Publisher.swift
- Example/Shared/Tests/InputConfig.swift
- NotifyTests.xctestplan
- run_tests.sh
> Configure gm dapp host

- Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Example/WalletApp/ApplicationLayer/ProfilingService.swift
> enable notify logs

- fastlane/Fastfile
Build for internal group is adding automatically. No need to specify it
> [CI] Release CI warning fix

- Example/IntegrationTests/Push/NotifyTests.swift
- Example/IntegrationTests/Push/Publisher.swift
- Example/Shared/Tests/InputConfig.swift
- Sources/WalletConnectNotify/Client/Wallet/NotifyClientFactory.swift
- Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyWatchSubscriptions/NotifyWatchSubscriptionsRequester.swift
- Sources/WalletConnectNotify/Notify.swift
- Sources/WalletConnectNotify/NotifyConfig.swift
> add notify host from env var

- Example/IntegrationTests/Push/NotifyTests.swift
- Example/WalletApp/PresentationLayer/Wallet/Notifications/NotificationsView.swift
- Example/WalletApp/PresentationLayer/Wallet/PushMessages/SubscriptionPresenter.swift
- Sources/WalletConnectNotify/Client/Wallet/NotifyClient.swift
- `subscribe` method async operation awaiting subscription response (fixed "Subscribe" button ui glitch)
- main view redesigned
- debounce on messagesPublisher
> [Notify] Main view redesign

- Sources/WalletConnectNotify/Client/Wallet/ProtocolEngine/wc_notifyWatchSubscriptions/NotifyWatchSubscriptionsResponseSubscriber.swift
Context: https://walletconnect.slack.com/archives/C03S6NN8NHF/p1696252122141569
> [Notify] Check cancellation after build subscriptions

- Example/ExampleApp.xcodeproj/project.pbxproj
- Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Example/WalletApp/Common/Extensions/UIKit/UIColor.swift
- Example/WalletApp/Common/VIPER/SceneViewController.swift
- Example/WalletApp/PresentationLayer/Wallet/Notifications/NotificationsPresenter.swift
- Example/WalletApp/PresentationLayer/Wallet/Notifications/NotificationsView.swift
- Example/WalletApp/PresentationLayer/Wallet/NotifySettings/NotifyPreferencesView.swift
- Example/WalletApp/PresentationLayer/Wallet/PushMessages/SubscriptionView.swift
- Sources/WalletConnectNotify/Client/Wallet/NotifyClient.swift
> [Notify Beta.1] Sample app components

- Example/WalletApp/PresentationLayer/Wallet/Notifications/Models/SubscriptionsViewModel.swift
- Example/WalletApp/PresentationLayer/Wallet/Notifications/NotificationsInteractor.swift
- Example/WalletApp/PresentationLayer/Wallet/Notifications/NotificationsPresenter.swift
- Example/WalletApp/PresentationLayer/Wallet/Notifications/NotificationsView.swift
- Example/WalletApp/PresentationLayer/Wallet/NotifySettings/NotifyPreferencesPresenter.swift
Task https://github.com/WalletConnect/WalletConnectSwiftV2/issues/1145
> [Notify] Messages badge

- Sources/WalletConnectVerify/OriginVerifier.swift
- Sources/WalletConnectVerify/VerifyClient.swift
- Sources/WalletConnectVerify/VerifyClientFactory.swift
- Sources/WalletConnectVerify/VerifyContext.swift
> Remove verify host

- Example/IntegrationTests/Stubs/PushMessage.swift
Need to sync this change with other platforms
> [Notify] Push body updated

- Sources/WalletConnectRelay/Dispatching.swift
> [Core] add bundle id to a header

- Example/PNDecryptionService/Info.plist
- Example/PNDecryptionService/NotificationService.swift
- Example/WalletApp/Other/Info.plist
- Example/WalletApp/WalletApp.entitlements
- Example/WalletApp/WalletAppRelease.entitlements
> [Sample] Apns icon

- Sources/WalletConnectRouter/Router/Router.swift
- Sources/WalletConnectRouter/Router/RouterImports.swift
> [Cocoapods] Router imports fix 

- Sources/WalletConnectModal/Extensions/Bundle.swift
- Sources/WalletConnectModal/Extensions/Image+Backport.swift
- Sources/WalletConnectModal/Extensions/View+Backport.swift
- Sources/WalletConnectModal/Modal/ModalContainerView.swift
- Sources/WalletConnectModal/Modal/ModalSheet.swift
- Sources/WalletConnectModal/Modal/Screens/GetAWalletView.swift
- Sources/WalletConnectModal/Modal/Screens/WalletDetail/WalletDetail.swift
- Sources/WalletConnectModal/Networking/Explorer/ExplorerAPI.swift
- Sources/WalletConnectModal/UI/Common/Toast.swift
- Sources/WalletConnectModal/UI/Common/Web3ModalPicker.swift
- WalletConnectSwiftV2.podspec
`pod lib lint --allow-warnings` passing locally
> [WCM] Cocoapods support

- .github/workflows/ci.yml
> [Tests] GM removed

- Sources/WalletConnectNotify/Client/Wallet/NotifyIdentityService.swift
> [Notify] Statement updated

- Sources/WalletConnectVerify/VerifyClient.swift
> fix verify

- Example/IntegrationTests/Push/NotifyTests.swift
> [Hotfix] Notify update test disabled

- Example/WalletApp/PresentationLayer/Wallet/SessionProposal/SessionProposalInteractor.swift
- Sources/Web3Wallet/Web3WalletDecryptionService.swift
> [W3W] SessionPropose hotfix

- Example/PNDecryptionService/NotificationService.swift
> [Notify] message_id logging

- Example/DApp/DApp.entitlements
- Example/DApp/SceneDelegate.swift
- Example/ExampleApp.xcodeproj/project.pbxproj
> fix dapp keychain issue

- Example/WalletApp/PresentationLayer/Wallet/NotifySettings/NotifyPreferencesView.swift
- Example/WalletApp/PresentationLayer/Wallet/PushMessages/SubscriptionView.swift
- Sources/WalletConnectNotify/Client/Wallet/NotifyConfig.swift
- Sources/WalletConnectNotify/Client/Wallet/NotifyImageUrls.swift
- Sources/WalletConnectNotify/Client/Wallet/NotifySubscriptionsBuilder.swift
- Sources/WalletConnectNotify/Types/DataStructures/NotifySubscription.swift
- Tests/NotifyTests/Stubs/NotifySubscription.swift
> [Notify] Notification type image

- Example/RelayIntegrationTests/RelayClientEndToEndTests.swift
- Sources/WalletConnectHistory/HistoryNetworkService.swift
- Sources/WalletConnectRelay/ClientAuth/ClientIdAuthenticator.swift
- Sources/WalletConnectRelay/RelayClientFactory.swift
- Tests/RelayerTests/AuthTests/SocketAuthenticatorTests.swift
- Tests/RelayerTests/DispatcherTests.swift
> Client id authenticator fix

- Example/WalletApp/BusinessLayer/ListingsSertice/ListingsAPI.swift
- Example/WalletApp/PresentationLayer/Wallet/PushMessages/SubscriptionView.swift
> [Sample] UX fixes

- Package.swift
> [CI] Release pipeline fix

- Example/Shared/Signer/ETHSigner.swift
- Example/Shared/Signer/Signer.swift
> fix crash on sendTransaction request

- WalletConnectSwiftV2.podspec
> add dependency to podspec

- Example/WalletApp/PresentationLayer/Wallet/AuthRequest/AuthRequestPresenter.swift
- Example/WalletApp/PresentationLayer/Wallet/AuthRequest/AuthRequestView.swift
- Sources/WalletConnectSign/Auth/Services/SessionNamespaceBuilder.swift
- Tests/WalletConnectSignTests/SessionNamespaceBuilderTests.swift
> Sample app  sign one cacao

- Example/WalletApp/ApplicationLayer/SceneDelegate.swift
- Sources/WalletConnectModal/Modal/Screens/WalletList.swift
- Sources/WalletConnectPairing/PairingClient.swift
- Sources/WalletConnectSign/Sign/SignClient.swift
- Sources/WalletConnectSign/Sign/SignClientProtocol.swift
- fix crash: https://github.com/WalletConnect/WalletConnectSwiftV2/blob/c2802116f6e21df8d4fe587e289309776e8b015c/Sources/WalletConnectModal/Modal/Screens/WalletList.swift#L218
- remove method:  authenticate on existing pairing topic
- sample app links fix
> Link mode fixes

- Example/DApp/SceneDelegate.swift
- Sources/WalletConnectSign/Auth/Services/App/AuthResponseSubscriber.swift
> upgrade on link mode auth response

- Sources/WalletConnectSign/Auth/Link/LinkEnvelopesDispatcher.swift
> fix linkmode response encoding

- Example/ExampleApp.xcodeproj/project.pbxproj
- Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> W3m upgrade

- .swiftpm/xcode/xcshareddata/xcschemes/WalletConnect-Package.xcscheme
- Example/ExampleApp.xcodeproj/project.pbxproj
- Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Example/Shared/Signer/Signer.swift
- Example/WalletApp/BusinessLayer/AccountMock.swift
- Example/WalletApp/PresentationLayer/Wallet/Main/MainModule.swift
- Package.swift
- Sources/YttriumWrapper/YttriumWrapper.swift
> feat(smart accounts): update smart account library package

- Example/DApp/SceneDelegate.swift
> update rn link mode

- Sources/WalletConnectVerify/VerifyContextFactory.swift
- Tests/VerifyTests/VerifyContextFactoryTests.swift
> fix bug when url does not have scheme

- Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Sources/WalletConnectPush/Resources/PrivacyInfo.xcprivacy
> update push privacy file
